// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Health Состояние сервиса
type Health struct {
	// Status Всегда ok — иначе сервис не ответил бы
	Status HealthStatus `json:"status"`
}

// HealthStatus Всегда ok — иначе сервис не ответил бы
type HealthStatus string

// Problem Ошибка по RFC 9457. Решение принимается по code, тексты — для разработчика
type Problem struct {
	// Code Стабильный машинный код ошибки; клиенты переводят текст по нему
	//
	// Example: validation.failed
	Code string `json:"code"`

	// Detail Уточнение для разработчика; приходит не всегда, пользователю не показывать
	//
	// Example: Тело запроса не разбирается как JSON
	Detail *string `json:"detail,omitempty"`

	// Errors Ошибки по полям — только у validation.failed
	Errors *[]struct {
		// Code Нарушенное правило схемы: required, minLength, maximum, enum, format…
		//
		// Example: minLength
		Code string `json:"code"`

		// Field body.<путь через точку>, query.<имя>, path.<имя> или header.<имя>
		//
		// Example: body.name
		Field string `json:"field"`
	} `json:"errors,omitempty"`

	// RequestId Id запроса — по нему запрос находится в логах сервера
	//
	// Example: wf-api-7d9f/Yx3kQp1bZt-000042
	RequestId *string `json:"request_id,omitempty"`

	// Status HTTP-статус ответа, продублированный в теле
	//
	// Example: 400
	Status int `json:"status"`

	// Title Техническая сводка — текст HTTP-статуса; пользователю не показывать
	//
	// Example: Bad Request
	Title string `json:"title"`

	// Type Тип проблемы по RFC 9457; сейчас всегда about:blank — смысл несёт code
	//
	// Example: about:blank
	Type string `json:"type"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Проверка живости сервиса
	// (GET /v1/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetHealth Проверка живости сервиса
// (GET /v1/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/health", wrapper.GetHealth)
	})

	return r
}

type ProblemApplicationProblemPlusJSONResponse Problem

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetHealthdefaultApplicationProblemPlusJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Проверка живости сервиса
	// (GET /v1/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"pFjfbtvI9X6VAX+/CzulZNpJN135KrtFuk6LJt04CLqxEdLi2OJGIrUUlcQNDOjPJk6hIEYWe1Es2myz",
	"BXotyVbCyLb0Cue8wj5Jcc4MqX90skVvDJlDzpzzzXe+8808MYpBpRr40o9qRuGJEcpaNfBrkv+5FQY7",
	"ZVmhn8XAj6Qf0U+nWi17RSfyAn+lqt741de1wKexWrEkKw79+v9Q7hoF4/9WJvOvqNHaSjLvwcGBabiy",
	"Vgy9Kk1nFAx4jc8hhh4MoSugL/BbGGEDzqCLLRiIL69/Lj698uurBn2pp6PVvpBOOSpxdK7r0VxO+VYY",
	"VGUYeZTLrlOuyYW13sAIm9iCER7BOcQwENiEATagDzE2oWuYRnVqkidGLXKiOv+am+k7+hCO4QS6Ingg",
	"fm58LyCGc+ji4dysAs5hIGCELejDAFsQw6mAHnYM05B+vWIU7hnBA2PbNKL9qjQKRi0KPX+PEw7lN3Uv",
	"lC69o0OZvBfsfC2LkXFgTm/bh8AdwyjFMy/gnzDA5zDQQMAYG5xBTNhToNjEI/VRMXClKWg/YEj4YUcl",
	"fAKneCSwAV14x397lCYeQgzDDDBpmowY32CLP43hFF/AOXbgveD9f87x6AdDGMEJwZgkFK/Tw1MKHs45",
	"Jhgz6gPo07t4hK2pmFUmtBdwhm3C/rFTqZYJyIdO2XOZ3vldxytL11jYC2JS5HjljPD/xXw65Jk1lB/G",
	"ZV1jjU8pTIixpSnSn3DK5HAZkHcwgr6qBjjFl/pdGh3y/B01ii9mcoKf6HXK+B10eb0REVx9rSIjyLEx",
	"vdc04VDcuH3zj1kIyDAMwtoHSRZrlFXsR3DGPMGWTmUII4FtkYW3F8lK7aPl/Iv49A/oYgPbmtvnMErY",
	"3aWCZFCwiU+ZCJ2CSGrMFBXP/4P096KSKSrOY69Sr5iCKtQUu0FYcaKfG/+ewTh9PwutXU+W3cXodgJ3",
	"P79Vt6zLRRhjm/ZN4KHm7TuhuTTENr8jTfFNXYbpFzGc4VEyUnWiUsaA4BxjUZKOK8OMF2Zy4Hh8pyKN",
	"j+mPSshUqGepkH7ghKGzb+iPZS2672XAsOHOE5MFZbpEZ14QLK1pwSi69gVtJhzTyERy6W93JsdHuzmn",
	"6uWuup/urvz58eUHf6qu7nwV5SzLsq6sZe3dRar/xebmrRw3ECq4NjanZZ1rlqKFE2xDj/aA/+tDd6Ji",
	"faVIpzCYjvCKZaVReH4k92TIgHpROYvgP8EAn5LWMHGaVLYkN02lezDUaE5p30LgSoX+J4X5zHHFl2qL",
	"szBUDzJij2GcAEUgcRXO9qZ13kx4j4fQxeaMLgpnJ6hHhZ2y46umi036HpvUU88JDXyFLW5YM8FOffZR",
	"ovNogn5KhguJT3yRxXroRfu3yZ8obdqRTijDya/rrCBGwbhxd9OY9yXXikVZq+VYJ4ekWmLpxt3NZark",
	"d5S+4j3bI92mifdvk4azTgO3Hzl7ezJUdTRk2RszFa7Vo1IQen/hXDhAo6CDmkBRiqKqcmeevxtk7NuP",
	"KacPNZev3drIiua9WPJu3jbFNd8NA8+lJARVCPSgmxfwWjfpLj6DGGKBTVXnZ9zgzwS2WAl72MaX2FJj",
	"x8RT5ugIhlu+nWTELaQgPuNchBI6Zx5KfiztdQGjuaWhx5KbLq81qMvYKR9EmQ7yW/6WD6+hh3+FeL6X",
	"dJNur1iKT+fXeV+gz3Pi0qXpPnnpEi9mX2StbbGUVIOZdivoCltbPXs5L+CHifuhlk5ujpv5li9m+vBL",
	"YRN3baH685RHYvNxkUdaFzbXAH9nK/9j/xLjZ/IUHIV6caIlzIEfaGnsmARVCurHUBQ2KWPoO2XbFLbu",
	"LXnPZzNhm7Ra+jQKgvtlJ9yT9OqC27DFEjbZBMCYbb9ingKLdIfKyVZux15WM1N95P0gur8b1H3XNvWT",
	"ioxKgXufBpxyOXgkXTsv4A2DG2vPip35ZGIFYl/AAF+pQT59MOnivGLLhisr1SCSfnE/93u5rwnDiB0R",
	"jlqtU8O8UCiC9pCOG2yGXhLOmbgy3fuJyT7Fl3golu7c2fjtMg11eRtp797CibJSJ6zNTW58cdIpFvvI",
	"kancTEuQNkzmVpqhvurzGw09Cak4DFSODdV1VFtvJZAtLJ3wjOJX+3c+8Qcn0FdxY0eDCt/RYmSFNJ4b",
	"t2+K33xirdJu3Nn8XCzZa9baJ7lVK2etbq5eLVhWwbK+spfXBZxxd2klhrKfzKTOKkR+ipZqAFvTpnoM",
	"IwqRH76HM0aJG+wxp66VXXm2xDgn4X7P1f0CjlPFwGfK18NA8FIE2Yi5dManJZryHDu00wOqb8bjGTuk",
	"JebjmCAkCVqm1WhLmunhiuCiJ3SYImSurK1eTULJPk8ktOSEeooHZLzFqoC/Qwyv+HP4UZVWWqH3Pdfm",
	"oCfHuUEyUVfzKObzPzf+EWkgjLRckNlhcZv2EDAozNvHDMc44yin7WN+y09bfsG4e11U6ztlr0hNzjCN",
	"hzKsqT5o5VfzFtmboCp9p+oZBeNy3spfprOuE5W49a88XF0ppdcTezLKPDIp23iomCLWLMtMZVKnRluN",
	"TYr0LcQUbZxxSJ/JCTvrtAuss0R/bTzxqd6gsTakA2zgUcLQ/JYPr1Qn7LJgcEOBGL9Vaq4kKy/gbyyY",
	"utSxnTKcQObKoMCOlZYqNVcoiGJJFh/Mntap5So+H3Kr7mFny0+OpdjWe/ZCuPKh8q0DOIeTGZVIcubb",
	"HLGkZa0/UcN0o8+UPSGwYjhhNSEt0yVDOWNnWTGAjpfcKzZco2D8Tkb6nsmcvSdbs6wP3JH9d3djeoWs",
	"q7E307dITAJ1E7Hr1MvRRfOmgU7duk0sqlG4t20atXql4oT7ytilnFDc43WSHV28H4ucvRq55GrZiehY",
	"TI74cY67ZY5cBg1uH8wtOfHD97YPttNJFq+C4BTbtFfQU94rw7WNyXVhK7knTO6ipsLGF3Nhi0RaT1gw",
	"WMHNmZqgI9uQmdjnZbHJQksSQgUXG6bBh+TCJO8DTtzxA3+/EtRruUo94u2vKYhnMMkVg0qFUrxnJC7G",
	"MI05EzP1JDUwJD4ZtyWzdiR5sOhGjO2D/wwA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
