// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Health Состояние сервиса
type Health struct {
	// Status Всегда ok — иначе сервис не ответил бы
	Status HealthStatus `json:"status"`
}

// HealthStatus Всегда ok — иначе сервис не ответил бы
type HealthStatus string

// Problem Ошибка по RFC 9457. Решение принимается по code, тексты — для разработчика
type Problem struct {
	// Challenge Задача антибота — только у humancheck.required. Формат протокола ALTCHA, поля в camelCase, как их ждёт виджет ALTCHA: найдите число от 0 до maxNumber, при котором SHA-256(salt + число) в hex равен challenge, и повторите запрос с решением в заголовке X-WF-Humancheck (base64 от JSON с полями algorithm, challenge, number, salt, signature)
	Challenge *struct {
		// Algorithm Хеш-функция задачи; сейчас всегда SHA-256
		//
		// Example: SHA-256
		Algorithm string `json:"algorithm"`

		// Challenge SHA-256 от salt и искомого числа, hex
		//
		// Example: 4d5b2c0e7f9a1b3c5d7e9f0a2b4c6d8e0f1a3b5c7d9e1f2a4b6c8d0e2f4a6b8c
		Challenge string `json:"challenge"`

		// MaxNumber Верхняя граница перебора
		//
		// Example: 100000
		MaxNumber int64 `json:"maxNumber"`

		// Salt Соль с параметрами срока задачи (expires, Unix-время) и ключа подписи (kid)
		//
		// Example: b1946ac92492d2347c62?expires=1790000000&kid=Hx3k9QpLm2s&
		Salt string `json:"salt"`

		// Signature HMAC-SHA-256 задачи на ключе сервера, hex
		//
		// Example: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
		Signature string `json:"signature"`
	} `json:"challenge,omitempty"`

	// Code Стабильный машинный код ошибки; клиенты переводят текст по нему
	//
	// Example: validation.failed
	Code string `json:"code"`

	// Detail Уточнение для разработчика; приходит не всегда, пользователю не показывать
	//
	// Example: Тело запроса не разбирается как JSON
	Detail *string `json:"detail,omitempty"`

	// Errors Ошибки по полям — только у validation.failed
	Errors *[]struct {
		// Code Нарушенное правило схемы: required, minLength, maximum, enum, format…
		//
		// Example: minLength
		Code string `json:"code"`

		// Field body.<путь через точку>, query.<имя>, path.<имя> или header.<имя>
		//
		// Example: body.name
		Field string `json:"field"`
	} `json:"errors,omitempty"`

	// RequestId Id запроса — по нему запрос находится в логах сервера
	//
	// Example: wf-api-7d9f/Yx3kQp1bZt-000042
	RequestId *string `json:"request_id,omitempty"`

	// Status HTTP-статус ответа, продублированный в теле
	//
	// Example: 400
	Status int `json:"status"`

	// Title Техническая сводка — текст HTTP-статуса; пользователю не показывать
	//
	// Example: Bad Request
	Title string `json:"title"`

	// Type Тип проблемы по RFC 9457; сейчас всегда about:blank — смысл несёт code
	//
	// Example: about:blank
	Type string `json:"type"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Проверка живости сервиса
	// (GET /v1/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetHealth Проверка живости сервиса
// (GET /v1/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/health", wrapper.GetHealth)
	})

	return r
}

type ProblemResponseHeaders struct {
	RetryAfter *int
}
type ProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ProblemResponseHeaders
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response GetHealthdefaultApplicationProblemPlusJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Проверка живости сервиса
	// (GET /v1/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"pFltb9tWsv4rB7z3g51SCiXLbzKKCzcXuUlvt02bBNltHFgUeWSxlkiVpFJ7CwOW3dQpnI2RosAuit12",
	"0337KitWzNiW/Bfm/IX+ksXMOaQoiUlabBAkNl/OmZnzzDPPDL/ULK/Z8lzuhoFW/lLzedDy3IDTL7d8",
	"r9rgTfzR8tyQuyH+aLZaDccyQ8dzr7bkE+98Fngu3gusOm+a+NN/+7ymlbX/ujpa/6q8G1yN193Z2dE1",
	"mweW77RwOa2swQ/iMURwDGfQZdBj4isYil24gK7Ygz775Po1tlyaX9R0rc5Nm/tk5yc89Ldzq7WQ+/jr",
	"xIr/gr7YhT6cMtGBMxjCuXiC/+OvfTgT+zCAEwaXMISe2KPtIrEnnrCfd79jYi/9wj4rFZeZb4a84TSd",
	"MM+3LM5tbmu6xrfMZqvBtfKcoafC0HRcp9luauWCroXbLa6VNccN+Qb30fudnfhZ8uMGNxthnWJs2w7a",
	"bzZu+V6L+6GDJ1IzGwGfithzGIoOGX4EA4igT46JXehBJDrQ1XStlVrkSy0IzbAdZETqW3wRXsAJdJm3",
	"Sf5DBAPoioOJVRkMoM9gKPagB32xBxGcMzgWhxgJF/29r3mb2oPE6SD0HXdD07WtHN8KuRs41QbPyUdD",
	"v80xEj7/vO343MaXlY2jBbzqZ9wKtR09jco3YecShglc8gz+Cn3xGPoqQnCJp0y/XEAXPRAdcSRfsjyb",
	"63jwCI6O2BOHMhIncC6OmNiFLpzSv8fovziACM4yomzVzUaDuxv8157nH6GLJyAO0IsuDCi6tBd0MzFZ",
	"bzdN16pzazMfhzDP4O+jxJHuDuk9SgDostUP7ly7sapL3KNj0GOW2eSNa2bAdYYuwRmDSDxi8BJOxDNc",
	"pgcRnMBLjJdaoIxI6MIrOMGkQZQcEOrOYUjwYAYGbsia5taH7WaV+7qKPe4wVOk2hAt2+8Zqrji/MBOY",
	"jZC9k1pmFi2r8y0Z+R4eIUtiqzOIpAup1MXzPYWucrrD8O9u+vjhAtekZ15QOIbQgzPos9/m7l3P3UjC",
	"yWaqZsAXStKT929/9CGuFUcMLiBiZmPD852w3tTTRrnKVXRGZ4Gz4Zph2+ezUyBJXs9A8z/Q5Jz4igjq",
	"THwNkTiSRkt0RCuSwV4hUtCuXip9VTjTxKSNro0n5Y4+DtZxO9RbMgZ0OhjySHHpBQwxhqPz6up4WGP7",
	"luz5atEy+GJt2SxU56x5e5Ev1wyzWC1ZC/YSN2oFc646by3ay7xQK5ql6oK1ZBu8WCuZC9UlK8vgBE9Z",
	"NIY8JR7BQBxhxF4QcAYQia8lL8hycExw6aYtLRj4R9dqnt80Q0nVCyVtmrl1DQORsfVzmZkKJl3a+YLo",
	"Rf4UMdEhwBNFpc6SzfCtluPzQGd3XWcrBz0y8kIczTKZLOfiqaQEhN8JXFK8Izaz6dizY+GuFpZLC6a1",
	"XCwtF+3iXGnRWij+j1r93cLisiH/rLUNo7iw6djv3tia21z+uPVBsxjIi1kBT0A87fWN36xeyyUwSTuF",
	"3DCyPVVC8N8MpCzXlhZsY6mwtFSyFu2F+WWzWOOmaVjz86ZtFObNuWqtVCtUi1WjulQsWnZh3l6wCvNV",
	"o2YYprE0bfhEWRnlWxrzaTipo007nFWEsEhknT+SNBxjORRPYCAO4RUjDn5M1UZdwMQ5wYSKy1W0QlEi",
	"bhpQxUlg2sNnxZHYS1UkWaewBMOF2B+L4EOz4dikzfI102mQNJk6S5uHptPIMP9vRKIHMIiZ8m1Vb0Wx",
	"uXhEoIzQNlIGKS5KaswTOCWmJSmHmFDPXsp8gFNxKO+KJ2M+wU/4OAwlthSrQ1e+LS3DkNNPSSWX9Qs5",
	"OysC3Pc9P3ijhIhUlBO2z6y9WfF2Qt4M3lr1J9RCNp7+ghwi9lXpGsAw1i5dqsXnpGLFIwLCYZnFUNdZ",
	"03E/4O5GWNex9KIE1RmqLZ1Jcvt5959jMU6ez4pWzeENe9q6qmdv55Ex5iy4FPukmcWBwu0pU1g6E/v0",
	"DNfZ523uJ29ESG7xnZYZ1jNuMPIxYlLrZzwwTnxoj2s2+VtpQDqksjgrvdUF0/fNbU29zINw3ckIw017",
	"EpgkF9MpOvYAI0WdJIyEa4/hYcILvDNBk2M+flHLmS0nt2gv167+bmtu8+NWofppmENCLxUzefs1Yv/G",
	"nTu3ctQ3YMLto1kjNd9VKg2pZx+O8Qzotx50RyzWk4x0Dv20hSXDSKxI1cvQCRtZAP8J+lipISLgoKbo",
	"It10JO/BmYpmivumDJcs9B8xzHumzT6RR5wVQ3khw/YILuNAYZAoC8c7jzdpNLPqtcNytWG6stcSHXwf",
	"VRSZLTokugmjaWNTr70V6HQ3jn4ChtcCH/HCrbbvhNu3sS2V3FTlps/90U/XY3n0/r072mT7smpZPAhy",
	"qtdAsT7z/r07KGLgFN2XuKfeXjVhiPuXccFZwRu3vzA3Nrgv8+iMaO+SoLDaDuue7/yefCEDtbIyahSK",
	"ehi25GjBcWtexrn9mGD6QGF59dbNLGtesRnno9s6W3Vt33NsqcR6pB27eQY/qCLdRW1O0k7m+YVUxoxU",
	"Xx+Oxb54KvbkvVG/MYSzNbcSe0QlpMzeI1+YJDpzMpR0mVdWGAwntoZjotxke8VBXYqd7HLR035+zV1z",
	"4Qc4Ft9ANFlLunG1lygVjyb3eVXG13PsypV0nbxyhTarvG4uVGEzcTboSbWCLquoRr4ym2fw/Uj9xM0a",
	"FfM1l43V4aesgtitqL4vpZFIfLxOI62wCuUAvVeR+qfyS9p6nZYgK+SDIy4hDHyPW4tDHUOVBPVtUWQV",
	"ZEbfNRsVnVVUbck7LomJio67JVdDz1tvmP4Gx0en1EaFzYiOHGVdjnoyFSzkHUynilQ7lVm5MuZH3vXC",
	"9ZrXdu2Krq40eVj37HW8YTYa3hfcruQZPKfgRkqzisNJZyIZxB6Dvngmb9LQiUAX5SlwfyaOl5dOY4o8",
	"JxpW0z3ULhWzHdbzbRf/426ISCL/SkZB7jGgsQOcEJ0i//cosb4hPh2muEUeBkG/F08lRjmEFklVQa6N",
	"JheUPPKl4Syey9SYD60pLiflfWLmkJI+ldREsjI2Z4zPYHpkQ67O0eIqAVJmUUMl9hWLxiObStLCVH7Z",
	"HAT3/oWjkMrELKSCIXFs3mx5IXet7fwm3173eTtQYSnGbE29HhP7yKIy2KKjLE7KMwyILE9Q28ILpKcx",
	"SxHDk9s57nrL9zZ8HgQUKXUMk3OeP9C07CIxRKZDX3wjnpExPXGokmMgjuJuYXIvn7ca5vZ62zUfmk7D",
	"rDZ4essUAGW6p9aksA71hJpoLIIt4Ss8Dgp/Z3Jci7vXOLWaedsJcLsxMEwMgHC3pKOWDXaPkap5LI/z",
	"hZqpnUB/Ni/p+ubIudz/823F2ERZRxhCJZeSjnWqUjEkUQyt2FVJF2USm8yfuMuVUJi5e/fm/87irS4d",
	"AZLnSziRvcxUMLOF3JEu24k9HEb2R2vHs8Q08uUiNIzqSx93peyTunov5qyprWOiT59nItBPoCftFocq",
	"qPBtPKJR8bx5+yO2tGAU8EDu3rnGZipFo7iQKxg5o3CnsFg2jLJhfFqZXWE0E8KdVUeXDHvksGCPBj2i",
	"k6AnPZ8mEBGk4IKiRAp3dOjdhN4UTcTmfkfl9QnmmzJYfC0b64mxbQ+tiNA2sYuIwJPuI03GQzTxiM1Q",
	"QbjEEKIGmCVKF08xq9V0A8OFV3CagZEpFQuLsSnZDX0MS3LoWOIAQc0KWEMieEavw4+ytiUlct2xK2T0",
	"aJ7SjxfqKhwpNqRKoVMOqnqN3Qapi7SIh355sn/LaNnGWrp0/5ZfcxPNXdbuXWetdrXhWKgyNV17yP1A",
	"ClEjX8gb2F94Le6aLUcra3N5Iz+HU2IzrJP2vvqwcLWefBba4GHmzEL2bQcSKaxoGHqiU5RreNSig5a+",
	"hAitjTK+gYz5JA5X8BRI6CD8VecnHqkDulQdIc5aEybNr7nwTErRLhFGX36/EF9JOSU1Q57Bn9JFQewn",
	"CMcgU2agYS8ke0s5JaPAqBiNj8tQ80o8H1CdPxaHa248FxL76syeMJs/lI1jP/niF7NE7DPRMptRtNYb",
	"sWFy0BeyP8BgRXBCbEIfOGTKoM/icFYiAOc7JNZu2lpZ+z8equ97+vhX1qJhvOEL66/7sqp2yPqw+jz9",
	"9Y5AIEeBNbPdCF+3bmJo6pvtqEfUyvcf6FrQbjZNf1t2VgkmJPZon/hEp79LhuZGgG1qq2GGOJfClnQr",
	"R3I1hzIfbz7Ymdhy1JDef7DzIFkkYxZ/LlUIHMvmJ6NtmtKhkjhSZtMwP212orROEpXZ18dyAmcmZ4TE",
	"Hm0rOkS0A/oeEEGk6RpNqcojv3fIcdP13O2m1w5yzXZIxx/IEI/FJGd5zSa6eF+L2whN1ya6iNSVpINA",
	"8skYV473A/GF6XZA07UsiY47ZX0Qz5C4OBvNVJATN1Jab+LOtDLTdG1SPGkPdv49AA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
