// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Health Состояние сервиса
type Health struct {
	// Status Всегда ok — иначе сервис не ответил бы
	Status HealthStatus `json:"status"`
}

// HealthStatus Всегда ok — иначе сервис не ответил бы
type HealthStatus string

// Problem Ошибка по RFC 9457. Решение принимается по code, тексты — для разработчика
type Problem struct {
	// Challenge Задача антибота — только у humancheck.required. Формат протокола ALTCHA, поля в camelCase, как их ждёт виджет ALTCHA: найдите число от 0 до maxNumber, при котором SHA-256(salt + число) в hex равен challenge, и повторите запрос с решением в заголовке X-WF-Humancheck (base64 от JSON с полями algorithm, challenge, number, salt, signature)
	Challenge *struct {
		// Algorithm Хеш-функция задачи; сейчас всегда SHA-256
		//
		// Example: SHA-256
		Algorithm string `json:"algorithm"`

		// Challenge SHA-256 от salt и искомого числа, hex
		//
		// Example: 4d5b2c0e7f9a1b3c5d7e9f0a2b4c6d8e0f1a3b5c7d9e1f2a4b6c8d0e2f4a6b8c
		Challenge string `json:"challenge"`

		// MaxNumber Верхняя граница перебора
		//
		// Example: 100000
		MaxNumber int64 `json:"maxNumber"`

		// Salt Соль с параметрами срока задачи (expires, Unix-время) и ключа подписи (kid)
		//
		// Example: b1946ac92492d2347c62?expires=1790000000&kid=Hx3k9QpLm2s&
		Salt string `json:"salt"`

		// Signature HMAC-SHA-256 задачи на ключе сервера, hex
		//
		// Example: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
		Signature string `json:"signature"`
	} `json:"challenge,omitempty"`

	// Code Стабильный машинный код ошибки; клиенты переводят текст по нему
	//
	// Example: validation.failed
	Code string `json:"code"`

	// Detail Уточнение для разработчика; приходит не всегда, пользователю не показывать
	//
	// Example: Тело запроса не разбирается как JSON
	Detail *string `json:"detail,omitempty"`

	// Errors Ошибки по полям — только у validation.failed
	Errors *[]struct {
		// Code Нарушенное правило схемы: required, minLength, maximum, enum, format…
		//
		// Example: minLength
		Code string `json:"code"`

		// Field body.<путь через точку>, query.<имя>, path.<имя> или header.<имя>
		//
		// Example: body.name
		Field string `json:"field"`
	} `json:"errors,omitempty"`

	// RequestId Id запроса — по нему запрос находится в логах сервера
	//
	// Example: wf-api-7d9f/Yx3kQp1bZt-000042
	RequestId *string `json:"request_id,omitempty"`

	// Status HTTP-статус ответа, продублированный в теле
	//
	// Example: 400
	Status int `json:"status"`

	// Title Техническая сводка — текст HTTP-статуса; пользователю не показывать
	//
	// Example: Bad Request
	Title string `json:"title"`

	// Type Тип проблемы по RFC 9457; сейчас всегда about:blank — смысл несёт code
	//
	// Example: about:blank
	Type string `json:"type"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Проверка живости сервиса
	// (GET /v1/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetHealth Проверка живости сервиса
// (GET /v1/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/health", wrapper.GetHealth)
	})

	return r
}

type ProblemResponseHeaders struct {
	RetryAfter *int
}
type ProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ProblemResponseHeaders
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response GetHealthdefaultApplicationProblemPlusJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Проверка живости сервиса
	// (GET /v1/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"pFn7bttW8n6VA/5+f9gppVCyfJNRLNwsskm326a5ILuNA5MSjyzWEqmSVGpvYcCy6zqFszFSFNhFsdtu",
	"urd/ZcWKGV/kV5jzCn2Sxcw5pCiJSVpsECQ2L+fMzPnmm2+GX2hVr9nyXO6GgVb+QvN50PLcgNMvt3yv",
	"0uBN/LHquSF3Q/zRarUaTtUKHc+92pJPvPNp4Ll4L6jWedPCn/7f5zWtrP3f1eH6V+Xd4Gq87tbWlq7Z",
	"PKj6TguX08oafC8eQwRHcApdBj0mvoSB2IZz6Iod6LPb16+xxdLsvKZrdW7Z3Cc7b/PQ38wt10Lu469j",
	"K/4H+mIb+nDCRAdOYQBn4gn+j7/24VTswgUcM7iEAfTEDm0XiR3xhP20/S0TO+kXdlmpuMh8K+QNp+mE",
	"eb5R5dzmtqZrfMNqthpcK88YeioMTcd1mu2mVi7oWrjZ4lpZc9yQr3Efvd/aip8lP25wqxHWKca27aD9",
	"VuOW77W4Hzp4IjWrEfCJiD2HgeiQ4YdwARH0yTGxDT2IRAe6mq61Uot8oQWhFbaDjEh9gy/CCziGLvPW",
	"yX+I4AK6Yn9sVQYX0GcwEDvQg77YgQjOGByJA4yEi/4+0Lx17WHidBD6jrum6dpGjm+E3A2cSoPn5KOh",
	"3+YYCZ9/1nZ8buPLysbhAl7lU14NtS09jco3YecSBglc8gz+Dn3xGPoqQnCJp0y/nEMXPRAdcShfqno2",
	"1/HgERwdsSMOZCSO4UwcMrENXTihf4/Qf7EPEZxmRLlatxoN7q7xX3qef4YunoDYRy+6cEHRpb2gm4nJ",
	"ertpudU6r67n4xDmGfxzmDjS3QG9RwkAXbb8wd1rN5Z1iXt0DHqsajV545oVcJ2hS3DKIBJ7DF7CsXiG",
	"y/QggmN4ifFSC5QRCV14BceYNIiSfULdGQwIHszAwA1Y09r4sN2scF9XsccdBirdBnDO7txYzhVn56YC",
	"qxGyd1LLTKNldb4hI9/DI2RJbHUGkXQhlbp4vifQVU53GP7dTh8/nOOa9MwLCscAenAKffb73P3ruRtJ",
	"ONlUxQr4XEl68v6djz7EteKIwTlEzGqseb4T1pt62ihXuYrO6Cxw1lwrbPt8egIkyesZaP4XmpwTXxJB",
	"nYqvIBKH0miJjmhJMtgrRAra1Uulrwpnmpi04bXRpNzSR8E6aod6S8aATgdDHikuPYcBxnB4Xl0dD2tk",
	"35I9WylWDT5fW7QKlZnqrD3PF2uGVayUqnP2AjdqBWumMludtxd5oVa0SpW56oJt8GKtZM1VFqpZBid4",
	"yqIx5CmxBxfiECP2goBzAZH4SvKCLAdHBJdu2tKCgX90reb5TSuUVD1X0iaZW9cwEBlbP5eZqWDSpZ3P",
	"iV7kTxETHQI8UVTqLNkU32g5Pg90ds91NnLQIyPPxeE0k8lyJp5KSkD4HcMlxTtiU+uOPT0S7kphsTRn",
	"VReLpcWiXZwpzVfnir9Sq79bmF805J+VtmEU59Yd+90bGzPrix+3PmgWA3kxK+AJiCe9vvG75Wu5BCZp",
	"p5AbhranSgj+m4GUxdrCnG0sFBYWStV5e2520SrWuGUZ1dlZyzYKs9ZMpVaqFSrFilFZKBardmHWnqsW",
	"ZitGzTAsY2HS8LGyMsy3NObTcFJHm3Y4qwhhkcg6fyRpOMJyKJ7AhTiAV4w4+DFVG3UBE+cYEyouV9ES",
	"RYm46YIqTgLTHj4rDsVOqiLJOoUlGM7F7kgEH1kNxyZtlq9ZToOkycRZ2jy0nEaG+f8gEt2Hi5gp31b1",
	"lhSbiz0CZYS2kTJIcVFSY57ACTEtSTnEhHr2UuYDnIgDeVc8GfEJfsTHYSCxpVgduvJtaRmGnH5KKrms",
	"X8jZWRHgvu/5wRslRKSinLB9Zu3NircT8mbw1qo/phay8fQ35BCxq0rXBQxi7dKlWnxGKlbsERAOyiyG",
	"us6ajvsBd9fCuo6lFyWozlBt6UyS20/b/x6JcfJ8VrRqDm/Yk9ZVPHszj4wxU4VLsUuaWewr3J4whaVT",
	"sUvPcJ191uZ+8kaE5BbfaVlhPeMGIx8jJrV+xgOjxIf2uFaTv5UGpEMqi7PSW12wfN/a1NTLPAhXnYww",
	"3LTHgUlyMZ2iIw8wUtRJwki49hgeJrzAO2M0OeLj57Wc1XJy8/Zi7eofNmbWP24VKp+EOST0UjGTt18j",
	"9m/cvXsrR30DJtwumjVU812l0pB6duEIz4B+60F3yGI9yUhn0E9bWDKMxIpUvQydsJEF8B+hj5UaIgIO",
	"aoou0k1H8h6cqmimuG/CcMlC/xPDvGfZ7LY84qwYygsZtkdwGQcKg0RZONp5vEmjWRWvHZYrDcuVvZbo",
	"4Puooshs0SHRTRhNG5t67a1Ap7tx9BMwvBb4iBdebftOuHkH21LJTRVu+dwf/nQ9lkfv37+rjbcvy9Uq",
	"D4Kc6jVQrE+9f/8uihg4Qfcl7qm3V00Y4v5lXHCW8Madz621Ne7LPDol2rskKCy3w7rnO38kX8hArayM",
	"GoaiHoYtOVpw3JqXcW4/JJjeV1hevnUzy5pXbMr56I7Oll3b9xxbKrEeacdunsH3qkh3UZuTtJN5fi6V",
	"MSPV14cjsSueih15b9hvDOB0xTVjj6iElNl75AuTRGeNh5Iuc3OJwWBsazgiyk22VxzUpdjJLhc97edX",
	"3BUXvocj8TVE47WkG1d7iVKxN77PqzK+nmNXrqTr5JUrtJn5urmQyabibNCTagVdZqpG3pzOM/huqH7i",
	"Zo2K+YrLRurwU2Yidk3V96U0EomP12mkJWZSDtB7ptQ/5s9p63VagqyQDw65hDDwHW4tDnQMVRLUt0WR",
	"mciMvms1TJ2ZqrbkHZfEhKnjbsnV0PNWG5a/xvHRCbVhsinRkaOsy2FPpoKFvIPpZEq1Y07LlTE/8q4X",
	"rta8tmuburrS5GHds1fxhtVoeJ9z28wzeE7BjZRmFQfjzkQyiD0GffFM3qShE4EuylPg/kocLy+dxBR5",
	"RjSspnuoXUyrHdbzbRf/426ISCL/SkZB7nFBYwc4JjpF/u9RYn1NfDpIcYs8DIJ+L55KDHMILZKqglwb",
	"Ti4oeeRLg2k8l4kxH1pTXEzK+9jMISV9zNRE0hyZM8ZnMDmyIVdnaHGVACmzqKESu4pF45GNmbQw5s+b",
	"g+DeP3MUYo7NQkwMiWPzZssLuVvdzK/zzVWftwMVlmLM1tTrMbGLLCqDLTrK4qQ8wwWR5TFqW3iB9DRi",
	"KWJ4fDvHXW353prPg4AipY5hfM7zJ5qWnSeGyHToi6/FMzKmJw5UclyIw7hbGN/L562Gtbnadq1HltOw",
	"Kg2e3jIFQJnuqTUprAM9oSYai2BL+AqPg8LfGR/X4u41Tq1m3nYC3G4EDGMDINwt6ahlg91jpGoey+N8",
	"oWZqx9Cfzku6vjl0LvdbvqkYmyjrEEOo5FLSsU5UKoYkiqEV2yrpokxik/kTd7kSClP37t389TTe6tIR",
	"IHm+hGPZy0wEM1vIHeqyndjBYWR/uHY8S0wjXy5Cw6i+9HFbyj6pq3dizprYOib69HkmAv0YetJu5Kr0",
	"flI3Y4KiWqPj3ZMTJ/FsKJYTbZ2ohHS6IUjN9CHdJgRyu8xwOG6qY4Rv4qGQOsGbdz5iC3NGASFw7+41",
	"NmUWjeJcrmDkjMLdwnzZMMqG8Yk5vcRoCoW+qh4yGS/J8cQOjZZEJ8FreiJOsCUQwzmdC2nqIcy6CaEq",
	"YorN/ZYK+hPMcGWw+Eq28mOD4h5aEaFtYhsjhtjqIzHHYzuxx6YoTpd4aKg6pqmIiKcYTjVPwQPCKzg/",
	"wciUioX52JTsEUKcCOTQkUQephErYNWK4Bm9Dj/IapoU5VXHNsno4QSnHy/UVchV/Eu1SSdYKIWA/Q3p",
	"mXTbAP3yeMeY0SSONJHpjjG/4iYqv6zdv85a7UrDqaKu1XTtEfcDKX2NfCFvYEfjtbhrtRytrM3kjfwM",
	"zqWtsE5q/+qjwtV68iFqjYeZUxKJ5n2JFFY0DD1RRso1PGrRQUtfQoTWRhlfXUZ8EgdLeAokrTDhVK8p",
	"9tQBXaoeFKe7CXfnV1x4JsVvlyiqL7+YiC+lgJMqJc/gL+kyJHYThGOQKTPQsBeyXkgBJ6PAqPyNDuhQ",
	"ZUs875OyOBIHK248iRK76syeMJs/kq1qP/nGGPNS7DMVAjaliLQ35N/koM9lR4LBiuCY+Is+qciUQZ/F",
	"wbREAE6USB7etLWy9hseqi+K+uh33aJhvOGb7i/7lqt2yPqU+zz9vZBAIIePNavdCF+3bmJo6ivxsCvV",
	"yg8e6lrQbjYtf1P2cgkmJPZon/hEJ7+EhtZagI1xq2GFOAnDJngjRwI5h40F3ny4NbblsAV+8HDrYbJI",
	"xvT/TOoeOJLtVkajNqF8JXGkzKbPB2mzE213nOjavj6SEzilOSUk9mhb0SGivaAvEBFEmq7RXKw89HuL",
	"HLdcz91seu0g12yHdPyBDPFITHJVr9lEFx9oceOi6dpY35K6kvQsSD4ZA9LRDiS+MNmAaLqW1RTgTlmf",
	"4DNENU5jMzXr2I2Uuhy7M6kFNV0bl2vaw63/DgA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
