// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package auditdb

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const insertAudit = `-- name: InsertAudit :exec

INSERT INTO audit_log (id, actor_user_id, actor_role, action, object_type, object_id, before, after, reason, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertAuditParams struct {
	ID          uuid.UUID
	ActorUserID *uuid.UUID
	ActorRole   *string
	Action      string
	ObjectType  string
	ObjectID    *uuid.UUID
	Before      []byte
	After       []byte
	Reason      *string
	Ip          *netip.Addr
	UserAgent   *string
}

// Аудит-лог (спека бэкенда §6.9, §10). Только вставка: изменение и удаление запрещены триггером.
func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ID,
		arg.ActorUserID,
		arg.ActorRole,
		arg.Action,
		arg.ObjectType,
		arg.ObjectID,
		arg.Before,
		arg.After,
		arg.Reason,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}
