// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auditdb

import (
	"context"
)

type Querier interface {
	// Аудит-лог (спека бэкенда §6.9, §10). Только вставка: изменение и удаление запрещены триггером.
	InsertAudit(ctx context.Context, arg InsertAuditParams) error
}

var _ Querier = (*Queries)(nil)
