// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appversion.sql

package appversiondb

import (
	"context"
)

const getAppVersions = `-- name: GetAppVersions :one
SELECT platform, min_version, recommended_version, store_url, version, updated_at
FROM app_versions
WHERE platform = $1
`

// Версии приложения платформы; 0 строк — версии не заведены (публичная ручка отдаёт null-поля).
func (q *Queries) GetAppVersions(ctx context.Context, platform string) (AppVersion, error) {
	row := q.db.QueryRow(ctx, getAppVersions, platform)
	var i AppVersion
	err := row.Scan(
		&i.Platform,
		&i.MinVersion,
		&i.RecommendedVersion,
		&i.StoreUrl,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
