// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package appversiondb

import (
	"time"
)

type AppVersion struct {
	Platform           string
	MinVersion         string
	RecommendedVersion string
	StoreUrl           string
	Version            int64
	UpdatedAt          time.Time
}
