// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package appversiondb

import (
	"context"
)

type Querier interface {
	// Версии приложения платформы; 0 строк — версии не заведены (публичная ручка отдаёт null-поля).
	GetAppVersions(ctx context.Context, platform string) (AppVersion, error)
}

var _ Querier = (*Queries)(nil)
