// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Health Состояние сервиса
type Health struct {
	// Status Всегда ok — иначе сервис не ответил бы
	Status HealthStatus `json:"status"`
}

// HealthStatus Всегда ok — иначе сервис не ответил бы
type HealthStatus string

// Problem Ошибка по RFC 9457. Решение принимается по code, тексты — для разработчика
type Problem struct {
	// Code Стабильный машинный код ошибки; клиенты переводят текст по нему
	//
	// Example: validation.failed
	Code string `json:"code"`

	// Detail Уточнение для разработчика; приходит не всегда, пользователю не показывать
	//
	// Example: Тело запроса не разбирается как JSON
	Detail *string `json:"detail,omitempty"`

	// Errors Ошибки по полям — только у validation.failed
	Errors *[]struct {
		// Code Нарушенное правило схемы: required, minLength, maximum, enum, format…
		//
		// Example: minLength
		Code string `json:"code"`

		// Field body.<путь через точку>, query.<имя>, path.<имя> или header.<имя>
		//
		// Example: body.name
		Field string `json:"field"`
	} `json:"errors,omitempty"`

	// RequestId Id запроса — по нему запрос находится в логах сервера
	//
	// Example: wf-api-7d9f/Yx3kQp1bZt-000042
	RequestId *string `json:"request_id,omitempty"`

	// Status HTTP-статус ответа, продублированный в теле
	//
	// Example: 400
	Status int `json:"status"`

	// Title Техническая сводка — текст HTTP-статуса; пользователю не показывать
	//
	// Example: Bad Request
	Title string `json:"title"`

	// Type Тип проблемы по RFC 9457; сейчас всегда about:blank — смысл несёт code
	//
	// Example: about:blank
	Type string `json:"type"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Проверка живости сервиса
	// (GET /v1/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetHealth Проверка живости сервиса
// (GET /v1/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/health", wrapper.GetHealth)
	})

	return r
}

type ProblemApplicationProblemPlusJSONResponse Problem

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetHealthdefaultApplicationProblemPlusJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Проверка живости сервиса
	// (GET /v1/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"pFjdbhvHFX6VwbYXkrukVrIbN/RVmiKNmqJxYxtFYwnaFXckbcz9yXLpWDAE8Ce2XFCw6iAXRdEmdQr0",
	"mqJIe60f6hXOeYU8SXHOzC6X4spO0RuB2t2ZOeeb73znm3ls1EM/CgMZJE2j9tiIZTMKg6bkf27H4WZD",
	"+vSzHgaJDBL66URRw6s7iRcGS5H64hdfNMOA3jXrO9J36NfPY7ll1IyfLU3nX1Jvm0vZvHt7e6bhymY9",
	"9iKazqgZ8B0+gxSO4AQGAoYCv4YJtuEMBtiFsfjsow/F+zd+edOgkXo6Wu1j6TSSHY7OdT2ay2ncjsNI",
	"xolHuWw5jaacW+slTLCDXZjgIZxDCmOBHRhjG4aQYgcGhmlEhUkeG83ESVr869JM39BAOIYRDET4QPzY",
	"/lZACucwwP1Lswo4h7GACXZhCGPsQgqnAo6wb5iGDFq+UbtvhA+MddNIdiNp1IxmEnvBNiccyy9bXixd",
	"+kaHMv0u3PxC1hNjzyxu29vAvYBJjmdVwL9gjM9grIGAC2xzBilhT4FiBw/VoHroSlPQfsAJ4Yd9lfAI",
	"TvFQYBsG8Jr/HlGauA8pnJSASdOUxPgSuzw0hVM8gHPswxvB+/+M49EPTmACI4IxSyi9RQ9PKXg455jg",
	"glEfw5C+xUPsFmJWmdBewBn2CPtHjh81CMiHTsNzmd7VLcdrSNeY2wtiUuJ4jZLw/8182ueZNZRvx+WW",
	"xhqfUJiQYldTZDjllMnhMiCvYQJDVQ1wis/1t/T2hOfvq7d4MJMT/ECfU8avYcDrTYjgarSKjCDHdnGv",
	"acIT8bs7n/6hDAEZx2HcfCvJUo2yiv0Qzpgn2NWpnMBEYE+U4e0l0m++s5x/Ep/+CQNsY09z+xwmGbsH",
	"VJAMCnbwCROhXxNZjZnC94Lfy2A72TGF7zzy/JZvCqpQU2yFse8kP7b/M4Nx/n0ZWluebLjz0W2G7m51",
	"rWVZ1+twgT3aN4H7mrevhebSCfb4G2mKL1syzkekcIaH2ZvISXZKXgjOMRU70nFlXPLBTA4cT+D40niX",
	"/qiETIV6mQrpB04cO7uGHiybyYZXAsOqe5mYLCjFEp35QLC05gWj6DoUtJlwTG+mkkt/BzM5frVVcSKv",
	"ctN9f2vpz4+uP/hjtLz5eVKxLMu6sVK2d1ep/sd3796ucAOhguthpyjrXLMULYywB0e0B/zfEAZTFRsq",
	"RTqFcTHCG5aVR+EFidyWMQPqJY0ygv8AY3xCWsPE6VDZktx0lO7BiUazoH1zgSsV+r8U5teOKz5TW1yG",
	"oXpQEnsKFxlQBBJX4WxvusWbCW9wHwbYmdFF4WyGraS22XAC1XSxQ+OxQz31nNDAF9jlhjUTbGHYO4nO",
	"bzP0czJcSXzii6y3Yi/ZvUP+RBsH2Wx6YTCPwIdh+MCTiq4d7EAKqYABjOCMux33NbVTMJxSnRsGIaFK",
	"gNjj0Wx1ns0wDS5hovqG4/pesJGtPy3LyPtE7ioH5gVb4XxkH9xevRSJWODJqHoWFV+wy0JFnUOx5WBe",
	"4Z0oai7xwKqAv5LGqQ4NKX6tOiA+hRQPeWR9Ho61wL6chm2yAaBlWNqfz0CU48KSUMgAe9W1YC2A7+AI",
	"/zJ1OVkfGGSdWjEMnwiYaA/BIcKbGg2viGvXij3u2jWO3L7KFttiIWOymXcaGAhb2zR7sSrg71PnQu2Y",
	"nBg34rVAzPTQ58Im3tlC9daCv+HMr/I3t4TN/OVxtvIu9k8xbSZPwVGoD6c6AAOOm/StbxJUOajvQlHY",
	"pGpx4DRsU9i6L1S9gI2AbdJq+dMkDDcaTrwt6dM5p2CLBexwA4cLtuxkC880WKQZRAFbORV7Uc28kyRR",
	"NQiTja2wFbi2qZ/4MtkJ3Q164TQa4VfStasCXjK4qfab2L+cTKpAHAoY4wv1kk8ObP3SqmLLqiv9KExk",
	"UN+tfCJ3NWEYsUPCMaudrCtQozvmDCa8/ImgPeSKYbYTzqW4srsZZgb5FJ/jvli4d2/1N4v0asDbSHv3",
	"CkbKBo1YVzvctNJM5ed7wKGpnEhXwCsYT+fOdOiCl+Vq1JOQAsNY5dhWHUMVdTeDbG7pjGcUv9q/86ng",
	"jWCo4sa+BhW+ocXIxmg8V+98Kn71nrVMu3Hv7odiwV6xVt6rLFsVa/nu8s2aZdUs63OblOuM1aWbmcFh",
	"NpM6ZxD5KVqqAewWDfEFTChEfvgGzhglbo7HnPqEW5L2W5npzcL9lqv7AI5zxcCnypPDWPBSBNmEuaT0",
	"iqY8xz7t9Jjqm/F4yu5mgfl4QRCSBC3SarQlnfxgRHDREzoIETI3VpZvZqGUnwUyWnJCR4oHZJrFsoB/",
	"QAoveDh8r0orr9ANz7U56OlRbJxNNNA84u4guGlPSANhouWCjAqLW7H/w7h22fqVuL0ZN1i0ftW1IG/X",
	"NeNPHwluHeKD26uGaTyUserDhlVdrlrkTMJIBk7kGTXjetWqXqdjqpPscNdeeri8tJPfLGzLpPS0oxzf",
	"viKKWLEsM1dJnRk+Ve2MyielYNOS8/VMSti/RZvAMkvs154Rn+j9udBecoxtPMwIWl0L4AWfG2BwVZ+F",
	"tCrgb6yXutKxlxOcMObCoMCOlZQqMVcoiPqOrD+YPWjDIDvW7XPbP8L+WpCdKLGnt+xAuPKhspxjOIfR",
	"jEhkOfNFjFjQqjacimG+z2cwgVcKrBRGLCYkZbpiKGfsLyoC0MmQW8Wqa9SM38pEXxGZs1dcK5b1luut",
	"/+1aS69Qdqv1sngBxCRQlwhbTquRXDVvHmjhwmzqLo3a/XXTaLZ834l3aY3vp5xQ3ON1sh2dv9pKnO0m",
	"Gdyo4SR0oiUz+6jCzbJCJoNeru9dWrJgZe+v763ns8xf48Ap9miz4Ij72ni+dZJosd7qO77sHqkQNx5c",
	"iltk0jpiwWAFN/U1RocVlbSiXeKjp644T3iPM3aCMNj1w1az4rcS3vemwnYGjEo99H1O28jci2Eal8xL",
	"4UluXEh1Sm44Zm1I9mDehRjre/8dAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
