// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Health Состояние сервиса
type Health struct {
	// Status Всегда ok — иначе сервис не ответил бы
	Status HealthStatus `json:"status"`
}

// HealthStatus Всегда ok — иначе сервис не ответил бы
type HealthStatus string

// Problem Ошибка по RFC 9457. Решение принимается по code, тексты — для разработчика
type Problem struct {
	// Challenge Задача антибота — только у humancheck.required. Формат протокола ALTCHA, поля в camelCase, как их ждёт виджет ALTCHA: найдите число от 0 до maxNumber, при котором SHA-256(salt + число) в hex равен challenge, и повторите запрос с решением в заголовке X-WF-Humancheck (base64 от JSON с полями algorithm, challenge, number, salt, signature)
	Challenge *struct {
		// Algorithm Хеш-функция задачи; сейчас всегда SHA-256
		//
		// Example: SHA-256
		Algorithm string `json:"algorithm"`

		// Challenge SHA-256 от salt и искомого числа, hex
		//
		// Example: 4d5b2c0e7f9a1b3c5d7e9f0a2b4c6d8e0f1a3b5c7d9e1f2a4b6c8d0e2f4a6b8c
		Challenge string `json:"challenge"`

		// MaxNumber Верхняя граница перебора
		//
		// Example: 100000
		MaxNumber int64 `json:"maxNumber"`

		// Salt Соль с параметрами срока задачи (expires, Unix-время) и ключа подписи (kid)
		//
		// Example: b1946ac92492d2347c62?expires=1790000000&kid=Hx3k9QpLm2s&
		Salt string `json:"salt"`

		// Signature HMAC-SHA-256 задачи на ключе сервера, hex
		//
		// Example: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
		Signature string `json:"signature"`
	} `json:"challenge,omitempty"`

	// Code Стабильный машинный код ошибки; клиенты переводят текст по нему
	//
	// Example: validation.failed
	Code string `json:"code"`

	// Detail Уточнение для разработчика; приходит не всегда, пользователю не показывать
	//
	// Example: Тело запроса не разбирается как JSON
	Detail *string `json:"detail,omitempty"`

	// Errors Ошибки по полям — только у validation.failed
	Errors *[]struct {
		// Code Нарушенное правило схемы: required, minLength, maximum, enum, format…
		//
		// Example: minLength
		Code string `json:"code"`

		// Field body.<путь через точку>, query.<имя>, path.<имя> или header.<имя>
		//
		// Example: body.name
		Field string `json:"field"`
	} `json:"errors,omitempty"`

	// RequestId Id запроса — по нему запрос находится в логах сервера
	//
	// Example: wf-api-7d9f/Yx3kQp1bZt-000042
	RequestId *string `json:"request_id,omitempty"`

	// Status HTTP-статус ответа, продублированный в теле
	//
	// Example: 400
	Status int `json:"status"`

	// Title Техническая сводка — текст HTTP-статуса; пользователю не показывать
	//
	// Example: Bad Request
	Title string `json:"title"`

	// Type Тип проблемы по RFC 9457; сейчас всегда about:blank — смысл несёт code
	//
	// Example: about:blank
	Type string `json:"type"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Проверка живости сервиса
	// (GET /v1/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetHealth Проверка живости сервиса
// (GET /v1/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/health", wrapper.GetHealth)
	})

	return r
}

type ProblemResponseHeaders struct {
	RetryAfter *int
}
type ProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ProblemResponseHeaders
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response GetHealthdefaultApplicationProblemPlusJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Проверка живости сервиса
	// (GET /v1/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"pFl9b9vW9f4qF/z9/rBTSqZk+U1BMWQZumTt2jQv6NY6MCnyymYtkSpJpTYKA35J4hbO4qUosGHY2qV7",
	"+1dWrJqxJfkrnPsV+kmGc+4lRUlM0mJBkNh8ufecc5/znOccfqHZfrPle9yLQq36hRbwsOV7IadfbgV+",
	"rcGb+KPtexH3IvzRarUarm1Fru/NteQTb30a+h7eC+0N3rTwp/8PeF2rav83N1p/Tt4N55J1d3Z2dM3h",
	"oR24LVxOq2rwrfgSYjiBc+gw6DLxEIZiF/rQEfvQY7ffuc5WKgtLmq5tcMvhAdl5m0fBduFaPeIB/jqx",
	"4n+gJ3ahB2dM7ME5DOFCPMH/8dcenIsDGMApg0sYQlfs03ax2BdP2I+73zCxn33hgFXKKyywIt5wm25U",
	"5Fs25w53NF3jW1az1eBadd7QM2Foup7bbDe1aknXou0W16qa60V8nQfo/c5O8iz5cYNbjWiDYuw4Ltpv",
	"NW4FfosHkYsnUrcaIZ+K2HMYij0y/BgGEEOPHBO70IVY7EFH07VWZpEvtDCyonaYE6mv8UV4AafQYf4m",
	"+Q8xDKAjDidWZTCAHoOh2Icu9MQ+xHDB4EQcYSQ89PcTzd/U7qdOh1Hgeuuarm0V+FbEvdCtNXhBPhoF",
	"bY6RCPhnbTfgDr6sbBwt4Nc+5Xak7ehZVL4OO5cwTOFSZPB36IkvoaciBJd4yvRLHzrogdgTx/Il23e4",
	"jgeP4NgT++JIRuIULsQxE7vQgTP69wT9F4cQw3lOlO0Nq9Hg3jr/uef5J+jgCYhD9KIDA4ou7QWdXExu",
	"tJuWZ29we7OYhLDI4J+jxJHuDuk9SgDosGvv3b1+45oucY+OQZfZVpM3rlsh1xm6BOcMYvGIwQ9wKp7h",
	"Ml2I4RR+wHipBaqIhA68hFNMGkTJIaHuAoYED2Zg4IasaW29327WeKCr2OMOQ5VuQ+izOzeuFcoLizOh",
	"1YjYW5llZtGyDb4lI9/FI2RpbHUGsXQhk7p4vmfQUU7vMfy7mz1+6OOa9MwLCscQunAOPfa7wkfvFG6k",
	"4WQzNSvkixXpyW/ufPA+rpVEDPoQM6ux7gdutNHUs0Z5ylV0Rmehu+5ZUTvgs1MgSV/PQfO/0OSCeEgE",
	"dS4eQyyOpdESHfFVyWAvESloVzeTviqcWWLSRtfGk3JHHwfruB3qLRkDOh0Meay4tA9DjOHovDo6HtbY",
	"vhVnoVa2Db5UX7FKtXl7wVniK3XDKtcq9qKzzI16yZqvLdhLzgov1ctWpbZoLzsGL9cr1mJt2c4zOMVT",
	"Ho0hT4lHMBDHGLEXBJwBxOKx5AVZDk4ILp2spSUD/+ha3Q+aViSperGiTTO3rmEgcrZ+LjNTwaRDO/eJ",
	"XuRPMRN7BHiiqMxZshm+1XIDHursnuduFaBLRvbF8SyTyXIhnkpKQPidwiXFO2Yzm64zOxbuWmmlsmjZ",
	"K+XKStkpz1eW7MXyL9Tqb5eWVgz5Z7VtGOXFTdd5+8bW/ObKh633muVQXswLeAriaa9v/Pba9UIKk6xT",
	"yA0j2zMlBP/NQcpKfXnRMZZLy8sVe8lZXFixynVuWYa9sGA5RmnBmq/VK/VSrVwzasvlsu2UFpxFu7RQ",
	"M+qGYRnL04ZPlJVRvmUxn4WTOtqsw3lFCItE3vkjScMJlkPxBAbiCF4y4uAvqdqoC5g4p5hQSbmKr1KU",
	"iJsGVHFSmHbxWXEs9jMVSdYpLMHQFwdjEXxgNVyHtFmxbrkNkiZTZ+nwyHIbOeb/g0j0EAYJU76p6l1V",
	"bC4eEShjtI2UQYaL0hrzBM6IaUnKISbUs5cyH+BMHMm74smYT/A9Pg5DiS3F6tCRb0vLMOT0U1rJZf1C",
	"zs6LAA8CPwhfKyFiFeWU7XNrb1683Yg3wzdW/Qm1kI+nvyGHiANVugYwTLRLh2rxBalY8YiAcFRlCdR1",
	"1nS997i3Hm3oWHpRguoM1ZbOJLn9uPvvsRinz+dFq+7yhjNtXc13tovIGPM2XIoD0sziUOH2jCksnYsD",
	"eobr7LM2D9I3YiS35E7LijZybjDyMWZS6+c8ME58aI9nNfkbaUA6pLI4L73VBSsIrG1NvczDaM3NCcNN",
	"ZxKYJBezKTr2ACNFnSaMhGuX4WHCC7wzQZNjPn5eL1gtt7DkrNTnfr81v/lhq1T7OCogoVfKubz9CrF/",
	"4+7dWwXqGzDhDtCskZrvKJWG1HMAJ3gG9FsXOiMW60pGuoBe1sKKYaRWZOpl5EaNPIB/Dz2s1BATcFBT",
	"dJBu9iTvwbmKZob7pgyXLPQ/McwvLYfdlkecF0N5Icf2GC6TQGGQKAvHO4/XaTSr5rejaq1hebLXEnv4",
	"PqooMlvskegmjGaNzbz2RqDT3ST6KRheCXzEC7fbgRtt38G2VPWLPAxd35uOwHXf33S5hOseqhGIGVX/",
	"PlW7cylRqSR2R1BX8r+rUgDR4+JqNq2m6RqlMEJ9zXKarreW7D9Ky5b7Lt+W4wPXq/vTll27dXPCEjZD",
	"i2H2zEq8iH2lA2OFlpyO32q1wjl6scjgj8hxskJDLB7KCqh0Ob5pT4dj1TMn3TD1TOsjDsTTsRClcSFK",
	"yHggDoqr3qoH38KJ+GrUwyZ1oJNUaokw7NqGSkOQifCyiq8X2JUr2Rp35QpZbr5qpmOymQTJelppoMNM",
	"1YSbs0UGfxkpl6TRokK86rGxGvqUmYg7U/VsGX1Dnr9K31xlJuGX3jOldjF/Skuu0xJkhXxwxAPQIbuR",
	"3450DFUa1DdFkZnIaoFnNUydmaouFF2PhICp427p1cj31xpWsM7x0SmlYLIZsSfHUJejfkoFCzkDIWBK",
	"pWLOypU3oqhV9Pxore63PcfU1ZUmjzZ8Zw1vWI2G/zl3zCKD5xTcWOlNcTTpTCyD2GXQE8/kTRoYkfSL",
	"ixS4vxI/y0tnCb1dEIWqyRzqDtNqRxvFtof/cS9CJJF/FaMk9xjQyACzHV4S3LuIfPEVceFwRAZ4Zmh0",
	"Ok8gI87IACT24SwGfWr+hluVV9K6OzEMyGgSMzMqNMcGgEmAp2cp5Mc8La7QnZkxUKeDBT6Gs9EsxUx7",
	"C/OnDShw7584ozAnhhQmhsR1eLPlR9yzt4ubfHst4O1QhaUsw6KaMCYOcH5DYY3FnrI4rZswoNb1FJkJ",
	"XqDSGrMUATq5neuttQJ/PeBhSJFSxzA5gPkDjbH6qSES6z3xlXhGxnTFkUL+QBwnMn5yr4C3Gtb2Wtuz",
	"Hlhuw6o1eHbLDLpkLmfWpLAO9ZR3aF6BrPsyQRl6Nz5Hxd3rnHrAouOGuN0YGCYmM7hb2upS5ysewoU6",
	"v/5sUbLvzZE7hXf5tiJgYqBjDFpSixKVNQ6AIZwz5ESqQLsqh+JcnpIZkzSc8vBn7t27+atZvNWhoCMX",
	"/gCnsq2YCl++pjrWpbLfx7lgb7R2UtezWJeL0FyoJ33clQpMFsn9hIKmtk54O3uCqYA4ha60G6knu5+U",
	"sJiSKJzoQB/J4Y94NtKtqcwlqE8mGMLSzB7SbcIcd6oM59SmOkb4OpnPqBO8eecDtrxolDBr7929zmbM",
	"slFeLJSMglG6W1qqGkbVMD42UXv0SR/sJ+1cOumRk4J9mvKIvRSh2eE0AZVgC306F5K3L9QUFUWl6pgS",
	"KkrM/Ybq8xPMaWWweCy76omZbZcpxYFLDsQRYquHbJxM0MQjNkNxusRDQxExSzVBPMVwqtEGHhBewVEG",
	"RqZSLi0lpuR380kikEMnEnnIhqyERSiGZ/Q6fCeLY1pj11zHJKNHw5ReslBHIVcxLpUanWChCj62GiRP",
	"sgoeetXJ5i2nXxvr57LNW3HVSwV3VfvoHUbij127dVPTtQc8kEpaM4qlooG9hd/intVytao2XzSK8zgh",
	"tqIN0t1zD0pzG+knoXUe5c4rJJgPJVBY2TD0VOcoz8RjKUgxYWM0Ns75/jHmkji6iodAQgnzTXV94pE6",
	"n0vVDeKcNSXr4qoHz6jKQudVShniIoM/Z+uOOEgBjjGmxEDDXsgCIeWYjAKjejc+KsOpqoTzIQn3E3G0",
	"6iUzIXGgjuwJc/gD2TT20q99CS0lPhPzsxnFo90R/abn3Ieh+viB30GIvujjhswY9FkczUoA4GyHxN5N",
	"R6tqv+aR+ranj39hLRvGa76u/ryvqmqHvI+qz7Nf7ggEcgxYt9qN6FXrpoZmvteO+kOt+sl9XQvbzaYV",
	"bOMe340wIbFH+yQnOv1NMrLWQ2xRWw0rwpkUtqNbBZK7BWwT8Ob9nYktM83oJ/d37qer5AziL6TSgRPi",
	"/d60+J0WspI4MnbTJD9rd6rmTokwiMF1NYjcI0Yd0NR/uhMe9bWpwzvkseX53nbTb4eFZjuicw9lbMeC",
	"UbD9ZpPc1pL+Q9O1ifYjcyVtPZB1cmaU441EcmG6j9B0LU/b4055X8Fz5DO297nqdOJGRkdO3JlWfZqu",
	"TQoz7f7OfwcA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
