// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Health Состояние сервиса
type Health struct {
	// Status Всегда ok — иначе сервис не ответил бы
	Status HealthStatus `json:"status"`
}

// HealthStatus Всегда ok — иначе сервис не ответил бы
type HealthStatus string

// Problem Ошибка по RFC 9457. Решение принимается по code, тексты — для разработчика
type Problem struct {
	// Challenge Задача антибота — только у humancheck.required. Формат протокола ALTCHA, поля в camelCase, как их ждёт виджет ALTCHA: найдите число от 0 до maxNumber, при котором SHA-256(salt + число) в hex равен challenge, и повторите запрос с решением в заголовке X-WF-Humancheck (base64 от JSON с полями algorithm, challenge, number, salt, signature)
	Challenge *struct {
		// Algorithm Хеш-функция задачи; сейчас всегда SHA-256
		//
		// Example: SHA-256
		Algorithm string `json:"algorithm"`

		// Challenge SHA-256 от salt и искомого числа, hex
		//
		// Example: 4d5b2c0e7f9a1b3c5d7e9f0a2b4c6d8e0f1a3b5c7d9e1f2a4b6c8d0e2f4a6b8c
		Challenge string `json:"challenge"`

		// MaxNumber Верхняя граница перебора
		//
		// Example: 100000
		MaxNumber int64 `json:"maxNumber"`

		// Salt Соль с параметрами срока задачи (expires, Unix-время) и ключа подписи (kid)
		//
		// Example: b1946ac92492d2347c62?expires=1790000000&kid=Hx3k9QpLm2s&
		Salt string `json:"salt"`

		// Signature HMAC-SHA-256 задачи на ключе сервера, hex
		//
		// Example: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
		Signature string `json:"signature"`
	} `json:"challenge,omitempty"`

	// Code Стабильный машинный код ошибки; клиенты переводят текст по нему
	//
	// Example: validation.failed
	Code string `json:"code"`

	// Detail Уточнение для разработчика; приходит не всегда, пользователю не показывать
	//
	// Example: Тело запроса не разбирается как JSON
	Detail *string `json:"detail,omitempty"`

	// Errors Ошибки по полям — только у validation.failed
	Errors *[]struct {
		// Code Нарушенное правило схемы: required, minLength, maximum, enum, format…
		//
		// Example: minLength
		Code string `json:"code"`

		// Field body.<путь через точку>, query.<имя>, path.<имя> или header.<имя>
		//
		// Example: body.name
		Field string `json:"field"`
	} `json:"errors,omitempty"`

	// RequestId Id запроса — по нему запрос находится в логах сервера
	//
	// Example: wf-api-7d9f/Yx3kQp1bZt-000042
	RequestId *string `json:"request_id,omitempty"`

	// Status HTTP-статус ответа, продублированный в теле
	//
	// Example: 400
	Status int `json:"status"`

	// Title Техническая сводка — текст HTTP-статуса; пользователю не показывать
	//
	// Example: Bad Request
	Title string `json:"title"`

	// Type Тип проблемы по RFC 9457; сейчас всегда about:blank — смысл несёт code
	//
	// Example: about:blank
	Type string `json:"type"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Проверка живости сервиса
	// (GET /v1/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetHealth Проверка живости сервиса
// (GET /v1/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/health", wrapper.GetHealth)
	})

	return r
}

type ProblemResponseHeaders struct {
	RetryAfter *int
}
type ProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ProblemResponseHeaders
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response GetHealthdefaultApplicationProblemPlusJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Проверка живости сервиса
	// (GET /v1/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"pFltb9vWkv4rB9z9YKeUTMnym4Jikc2im2y7bdok6G7rwDoij2zWEqmSVGqjMOCXJG7hbLwpCuzi4t72",
	"pvftq6xYNWNb8l+Y8xf6Sy5mziFFSUzS4gZBYvPlnJk5zzzzzPBrw/Zbbd8TXhQa1a+NQIRt3wsF/XIn",
	"8OtN0cIfbd+LhBfhj7zdbro2j1zfm2urJ975IvQ9vBfaG6LF8ad/DkTDqBr/NDdaf07dDeeSdXd2dkzD",
	"EaEduG1czqga8IP8BmI4gXPoMugx+QiGchcuoSv3oc8+ee8mW6ksLBmmsSG4IwKy8xMRBduFG41IBPjr",
	"xIp/g77chT6cMbkH5zCEC/kU/8df+3AuD2AApwyuYAg9uU/bxXJfPmW/7H7P5H72hQNWKa+wgEei6bbc",
	"qCi2bCEc4RimIbZ4q90URnXeMjNhaLme2+q0jGrJNKLttjCqhutFYl0E6P3OTvIs+XFL8Ga0QTF2HBft",
	"5807gd8WQeTiiTR4MxRTEXsBQ7lHhh/DAGLok2NyF3oQyz3oGqbRzizytRFGPOqEOZH6Dl+El3AKXeZv",
	"kv8QwwC68nBiVQYD6DMYyn3oQV/uQwwXDE7kEUbCQ38/N/xN40HqdBgFrrdumMZWQWxFwgvdelMU1KNR",
	"0BEYiUB82XED4eDL2sbRAn79C2FHxo6ZReWbsHMFwxQuRQZ/hL78Bvo6QnCFp0y/XEIXPZB78li9ZPuO",
	"MPHgERx7cl8eqUicwoU8ZnIXunBG/56g//IQYjjPibK9wZtN4a2L33qe/wddPAF5iF50YUDRpb2gm4vJ",
	"jU6Le/aGsDeLSQiLDP48Shzl7pDeowSALrvxwb2bt26YCvfoGPSYzVuieZOHwmToEpwziOVjBj/DqXyO",
	"y/QghlP4GeOlF6giErrwCk4xaRAlh4S6CxgSPJiFgRuyFt/6sNOqi8DUsccdhjrdhnDJ7t66USgvLM6E",
	"vBmxdzLLzKJlG2JLRb6HR8jS2JoMYuVCJnXxfM+gq53eY/h3N3v8cIlr0jMvKRxD6ME59Nl/FT59r3Ar",
	"DSebqfNQLFaUJ/9x96MPca0kYnAJMePNdT9wo42WmTXK066iMyYL3XWPR51AzE6BJH09B81/QZML8hER",
	"1Ll8ArE8VkYrdMTXFYO9QqSgXb1M+upwZonJGF0bT8odcxys43bot1QM6HQw5LHm0ksYYgxH59U18bDG",
	"9q04C/WybYmlxgov1eftBWdJrDQsXq5X7EVnWViNEp+vL9hLzoooNcq8Ul+0lx1LlBsVvlhftvMMTvGU",
	"R2PIU/IxDOQxRuwlAWcAsXyieEGVgxOCSzdracnCP6bR8IMWjxRVL1aMaeY2DQxEztYvVGZqmHRp50ui",
	"F/VTzOQeAZ4oKnOWbEZstd1AhCa777lbBeiRkZfyeJapZLmQzxQlIPxO4YriHbOZTdeZHQt3vbRSWeT2",
	"SrmyUnbK85Ule7H8L3r1d0tLK5b6s9qxrPLipuu8e2trfnPl4/YHrXKoLuYFPAXxtNe3/vPGzUIKk6xT",
	"yA0j2zMlBP/NQcpKY3nRsZZLy8sVe8lZXFjh5Ybg3LIXFrhjlRb4fL1RaZTq5bpVXy6Xbae04CzapYW6",
	"1bAsbi1PGz5RVkb5lsV8Fk76aLMO5xUhLBJ5548kDSdYDuVTGMgjeMWIg7+haqMvYOKcYkIl5Sq+TlEi",
	"bhpQxUlh2sNn5bHcz1QkVaewBMOlPBiL4EPedB3SZsUGd5skTabO0hERd5s55v+JSPQQBglTvq3qXdds",
	"Lh8TKGO0jZRBhovSGvMUzohpScohJvSzVyof4Eweqbvy6ZhP8BM+DkOFLc3q0FVvK8sw5PRTWslV/ULO",
	"zouACAI/CN8oIWId5ZTtc2tvXrzdSLTCt1b9CbWQj6c/IIfIA126BjBMtEuXavEFqVj5mIBwVGUJ1E3W",
	"cr0PhLcebZhYelGCmgzVlskUuf2y+9exGKfP50Wr4YqmM21d3Xe2i8gY8zZcyQPSzPJQ4/aMaSydywN6",
	"Rpjsy44I0jdiJLfkTptHGzk3GPkYM6X1cx4YJz60x+Mt8VYaUA7pLM5Lb32BBwHfNvTLIozW3Jww3HYm",
	"gUlyMZuiYw8wUtRpwii49hgeJrzEOxM0OebjV40Cb7uFJWelMfffW/ObH7dL9c+iAhJ6pZzL268R+7fu",
	"3btToL4BE+4AzRqp+a5WaUg9B3CCZ0C/9aA7YrGeYqQL6GctrFhWakWmXkZu1MwD+E/Qx0oNMQEHNUUX",
	"6WZP8R6c62hmuG/KcMVC/xDD/Ct32CfqiPNiqC7k2B7DVRIoDBJl4Xjn8SaNxut+J6rWm9xTvZbcw/dR",
	"RZHZco9EN2E0a2zmtbcCne4m0U/B8FrgI16E3QncaPsutqW6XxRh6PredARu+v6mKxRc91CNQMyo+l9S",
	"tTtXEpVKYm8EdS3/ezoFED0urmbTaoZpUAoj1Ne403K9tWT/UVq23ffFthofuF7Dn7bsxp3bE5awGVoM",
	"s2dW4UXuax0Ya7TkdPy83Q7n6MUig/9FjlMVGmL5SFVArcvxTXs6HKtebdKNmplpfeSBfDYWojQuRAkZ",
	"D+RBcdVb9eAHOJHfjnrYpA50k0qtEIZd21BrCDIRXlXx9QK7di1b465dI8trr5vp1NhMgmQzrTTQZTXd",
	"hNdmiwx+N1IuSaNFhXjVY2M19BmrIe5qumfL6Bvy/HX65jqrEX7pvZrSLrVf05KbtARZoR4c8QB0yW7k",
	"tyMTQ5UG9W1RZDVktcDjzZrJarouFF2PhEDNxN3Sq5HvrzV5sC7w0SmlUGMzck+Noa5G/ZQOFnIGQqCm",
	"lEptVq28EUXtoudHaw2/4zk1U19piWjDd9bwBm82/a+EUysyeEHBjbXelEeTzsQqiD0Gfflc3aSBEUm/",
	"uEiB+z3xs7p0ltDbBVGonsyh7qjxTrRR7Hj4n/AiRBL5V7FKao8BjQww2+EVwb2HyJffEhcOR2SAZ4ZG",
	"p/MEMuKMDEBiH85i0Kfmb7hVeSWtuxPDgIwmqWVGhbWxAWAS4OlZCvkxT4trdGdmDNTpYIGP4Ww0S6ml",
	"vUXt1w0ocO9fOaOoTQwpahgS1xGtth8Jz94uborttUB0Qh2WsgqLbsKYPMD5DYU1lnva4rRuwoBa11Nk",
	"JniJSmvMUgTo5Haut9YO/PVAhCFFSh/D5ADmf2iMdZkaorDel9/K52RMTx5p5A/kcSLjJ/cKRLvJt9c6",
	"Hn/I3SavN0V2ywy6VC5n1qSwDs2Ud2hegaz7KkEZejc+R8XdG4J6wKLjhrjdGBgmJjO4W9rqUucrH8GF",
	"Pr/L2aJi39sjdwrvi21NwMRAxxi0pBYlKmscAEM4Z8iJVIF2dQ7FuTylMiZpONXhz9y/f/vfZvFWl4KO",
	"XPgznKq2Yip8+Zrq2FTKfh/ngv3R2kldz2JdLUJzob7ycVcpMFUk9xMKmto64e3sCaYC4hR6ym55pIMK",
	"3yXTEh3P23c/YsuLVglz6P69m2ymVrbKi4WSVbBK90pLVcuqWtZnNVQCl1St95PmKp27qL59n2Yuci/F",
	"S3ZUTLAhEMElRYnE5ks900SJp/uXhBgSc7+navkUM0wbLJ+oHndigtpjuv7jkgN5hCfdR25M5lnyMZsh",
	"fr/CEGJJnyWGls8wj/WgAcOFV3CwgJGplEtLiSn5vXUCS3LoROEAuYmVsCTE8Jxehx9VqUor3prr1Mjo",
	"0WijnyzU1TjS/EfEb1LW6fKLwp/EQlZPQ7862UrldE9j3VW2lSqueqn8rRqfvsdIirEbd24bpvFQBErX",
	"GlaxVLRQ6ftt4fG2a1SN+aJVnMd5LY82SAXPPSzNbaQfaNZFlDs9UB3UoQIKK1uWmaoO7Zl8ouQhpk+M",
	"xsY5XyPGXJJH1/EQSLYg+nUPJh/r87nSvRlOPVPqLK568JxqHnRfp1shLjL4/2wVkAcpwDHGlBho2EtF",
	"10ocqSgwqj7jgyuccSo4H5KMPpFHq14yoZEH+sieMkc8VC1cP/32lpBE4jPxMJvRrNYbkWF6zpcw1J8i",
	"8KsEkQl9alAZgz7Lo1kFAJy0kPS67RhV499FpL+0mePfO8uW9YZvnb/tG6feIe8T54vsdzQCgRrKNXin",
	"Gb1u3dTQzNfTUbdmVD9/YBphp9XiwTbu8eMIEwp7tE9yotNfCCO+HmLD2G7yCCdE2BxuFUh8FlC0480H",
	"OxNbZlrDzx/sPEhXyRmLXyjdASdU1/rTUnRaViriyNhNc/Ws3am2OiXCIAY39Vhwjxh1QDP46b501GWm",
	"Du+Qx9zzve2W3wkLrU5E5x6q2I4Fo2D7rRa5bSTdgGEaE81A5kraCCDr5EwMx2V9cmFa1Rumkae0cae8",
	"b9I5Yhab7VytOHEjo+om7kxrMMM0JmWS8WDn7wMA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
