// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cities.sql

package geodb

import (
	"context"

	"github.com/google/uuid"
)

const getCitySettings = `-- name: GetCitySettings :one
SELECT c.id, c.timezone, c.status::text AS status, co.code::text AS country_code,
       co.is_enabled AS country_enabled, co.currency::text AS currency, co.default_locale,
       co.min_signup_age, co.age_of_majority
FROM cities c
JOIN countries co ON co.id = c.country_id
WHERE c.id = $1::uuid
`

type GetCitySettingsRow struct {
	ID             uuid.UUID
	Timezone       string
	Status         string
	CountryCode    string
	CountryEnabled bool
	Currency       string
	DefaultLocale  string
	MinSignupAge   int16
	AgeOfMajority  int16
}

// Настройки города для других модулей (§7): без фильтра видимости — country_enabled в ответе.
func (q *Queries) GetCitySettings(ctx context.Context, id uuid.UUID) (GetCitySettingsRow, error) {
	row := q.db.QueryRow(ctx, getCitySettings, id)
	var i GetCitySettingsRow
	err := row.Scan(
		&i.ID,
		&i.Timezone,
		&i.Status,
		&i.CountryCode,
		&i.CountryEnabled,
		&i.Currency,
		&i.DefaultLocale,
		&i.MinSignupAge,
		&i.AgeOfMajority,
	)
	return i, err
}

const getVisibleCity = `-- name: GetVisibleCity :one
SELECT c.id, c.slug,
       coalesce(cn.name, c.name)::text AS name,
       c.status::text AS status,
       c.timezone,
       ST_Y(c.centroid::geometry)::float8 AS lat,
       ST_X(c.centroid::geometry)::float8 AS lon,
       c.region_id,
       coalesce(rn.name, r.name, '')::text AS region_name,
       co.code::text AS country_code,
       coalesce(con.name, co.name)::text AS country_name,
       co.currency::text AS currency,
       co.default_locale,
       co.phone_prefix,
       co.week_starts_on,
       co.min_signup_age,
       co.age_of_majority
FROM cities c
JOIN countries co ON co.id = c.country_id
LEFT JOIN regions r ON r.id = c.region_id
LEFT JOIN city_names cn ON cn.city_id = c.id AND cn.locale = $1::text
LEFT JOIN region_names rn ON rn.region_id = r.id AND rn.locale = $1::text
LEFT JOIN country_names con ON con.country_id = co.id AND con.locale = $1::text
WHERE c.id = $2::uuid AND co.is_enabled
`

type GetVisibleCityParams struct {
	Locale string
	ID     uuid.UUID
}

type GetVisibleCityRow struct {
	ID            uuid.UUID
	Slug          string
	Name          string
	Status        string
	Timezone      string
	Lat           float64
	Lon           float64
	RegionID      *uuid.UUID
	RegionName    string
	CountryCode   string
	CountryName   string
	Currency      string
	DefaultLocale string
	PhonePrefix   string
	WeekStartsOn  int16
	MinSignupAge  int16
	AgeOfMajority int16
}

// Город с правилами страны (CityDetails без районов); страна выключена или города нет — 0 строк.
func (q *Queries) GetVisibleCity(ctx context.Context, arg GetVisibleCityParams) (GetVisibleCityRow, error) {
	row := q.db.QueryRow(ctx, getVisibleCity, arg.Locale, arg.ID)
	var i GetVisibleCityRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Timezone,
		&i.Lat,
		&i.Lon,
		&i.RegionID,
		&i.RegionName,
		&i.CountryCode,
		&i.CountryName,
		&i.Currency,
		&i.DefaultLocale,
		&i.PhonePrefix,
		&i.WeekStartsOn,
		&i.MinSignupAge,
		&i.AgeOfMajority,
	)
	return i, err
}

const listActiveDistricts = `-- name: ListActiveDistricts :many
SELECT id, name FROM districts
WHERE city_id = $1::uuid AND archived_at IS NULL
ORDER BY name_normalized, id
`

type ListActiveDistrictsRow struct {
	ID   uuid.UUID
	Name string
}

// Районы города без архивных (§3.2).
func (q *Queries) ListActiveDistricts(ctx context.Context, cityID uuid.UUID) ([]ListActiveDistrictsRow, error) {
	rows, err := q.db.Query(ctx, listActiveDistricts, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveDistrictsRow
	for rows.Next() {
		var i ListActiveDistrictsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCities = `-- name: ListCities :many
SELECT c.id, c.slug,
       coalesce(cn.name, c.name)::text AS name,
       c.status::text AS status,
       c.timezone,
       ST_Y(c.centroid::geometry)::float8 AS lat,
       ST_X(c.centroid::geometry)::float8 AS lon,
       c.region_id,
       coalesce(rn.name, r.name, '')::text AS region_name,
       co.code::text AS country_code,
       coalesce(con.name, co.name)::text AS country_name,
       c.population,
       (CASE c.status WHEN 'live' THEN 0 WHEN 'pilot' THEN 1 ELSE 2 END)::bigint AS status_rank
FROM cities c
JOIN countries co ON co.id = c.country_id
LEFT JOIN regions r ON r.id = c.region_id
LEFT JOIN city_names cn ON cn.city_id = c.id AND cn.locale = $1::text
LEFT JOIN region_names rn ON rn.region_id = r.id AND rn.locale = $1::text
LEFT JOIN country_names con ON con.country_id = co.id AND con.locale = $1::text
WHERE co.is_enabled
  AND (coalesce(cardinality($2::text[]), 0) = 0
       OR c.status::text = ANY ($2::text[]))
  AND ($3::text = '' OR co.code = $3::text)
  AND ($4::text = ''
       OR c.name_normalized LIKE $4::text || '%'
       OR EXISTS (SELECT 1 FROM city_names qn
                  WHERE qn.city_id = c.id AND qn.name_normalized LIKE $4::text || '%'))
  AND (NOT $5::boolean
       OR (CASE c.status WHEN 'live' THEN 0 WHEN 'pilot' THEN 1 ELSE 2 END) > $6::bigint
       OR ((CASE c.status WHEN 'live' THEN 0 WHEN 'pilot' THEN 1 ELSE 2 END) = $6::bigint
           AND (c.population < $7::bigint
                OR (c.population = $7::bigint AND c.id > $8::uuid))))
ORDER BY status_rank, c.population DESC, c.id
LIMIT $9::bigint
`

type ListCitiesParams struct {
	Locale          string
	Statuses        []string
	Country         string
	QPrefix         string
	HasCursor       bool
	AfterRank       int64
	AfterPopulation int64
	AfterID         uuid.UUID
	RowLimit        int64
}

type ListCitiesRow struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Status      string
	Timezone    string
	Lat         float64
	Lon         float64
	RegionID    *uuid.UUID
	RegionName  string
	CountryCode string
	CountryName string
	Population  int64
	StatusRank  int64
}

// Публичный список городов (спека geo §4.2). Видимость — только страны is_enabled (§4.1).
// Названия: строка *_names запрошенной локали, иначе каноническое name (язык страны);
// locale = ” — локаль не согласована: строк с пустой локалью нет (CHECK ^[a-z]{2}$), все названия
// канонические. Регион: region_id NULL — региона нет, region_name тогда ”.
// Порядок: ранг статуса (live 0, pilot 1, waitlist 2), population по убыванию, id; курсор —
// строго после (after_rank, after_population, after_id) в этом порядке.
// statuses пуст — без фильтра; country ” — без фильтра; q_prefix ” — без поиска. q_prefix уже
// нормализован (normalize_text оставляет только [a-zа-яё0-9], поэтому % и _ в нём невозможны).
// Перед «||» — sqlc.arg(x), не @x: префиксный «@» захватил бы всё выражение (см. ratelimit.sql).
func (q *Queries) ListCities(ctx context.Context, arg ListCitiesParams) ([]ListCitiesRow, error) {
	rows, err := q.db.Query(ctx, listCities,
		arg.Locale,
		arg.Statuses,
		arg.Country,
		arg.QPrefix,
		arg.HasCursor,
		arg.AfterRank,
		arg.AfterPopulation,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCitiesRow
	for rows.Next() {
		var i ListCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.Timezone,
			&i.Lat,
			&i.Lon,
			&i.RegionID,
			&i.RegionName,
			&i.CountryCode,
			&i.CountryName,
			&i.Population,
			&i.StatusRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nearestOpenCity = `-- name: NearestOpenCity :one
SELECT c.id, c.slug,
       coalesce(cn.name, c.name)::text AS name,
       c.status::text AS status,
       c.timezone,
       ST_Y(c.centroid::geometry)::float8 AS lat,
       ST_X(c.centroid::geometry)::float8 AS lon,
       c.region_id,
       coalesce(rn.name, r.name, '')::text AS region_name,
       co.code::text AS country_code,
       coalesce(con.name, co.name)::text AS country_name,
       ST_Distance(c.centroid,
                   ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography)::float8
         AS distance_m
FROM cities c
JOIN countries co ON co.id = c.country_id
LEFT JOIN regions r ON r.id = c.region_id
LEFT JOIN city_names cn ON cn.city_id = c.id AND cn.locale = $3::text
LEFT JOIN region_names rn ON rn.region_id = r.id AND rn.locale = $3::text
LEFT JOIN country_names con ON con.country_id = co.id AND con.locale = $3::text
WHERE co.is_enabled AND c.status IN ('pilot', 'live')
ORDER BY c.centroid <-> ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
         c.id
LIMIT 1
`

type NearestOpenCityParams struct {
	Lon    float64
	Lat    float64
	Locale string
}

type NearestOpenCityRow struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Status      string
	Timezone    string
	Lat         float64
	Lon         float64
	RegionID    *uuid.UUID
	RegionName  string
	CountryCode string
	CountryName string
	DistanceM   float64
}

// Ближайший видимый город pilot/live по centroid без ограничения расстояния (§4.3): KNN «<->»
// по GiST-индексу, расстояние — ST_Distance по geography (сфероид, антимеридиан учтён).
func (q *Queries) NearestOpenCity(ctx context.Context, arg NearestOpenCityParams) (NearestOpenCityRow, error) {
	row := q.db.QueryRow(ctx, nearestOpenCity, arg.Lon, arg.Lat, arg.Locale)
	var i NearestOpenCityRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Timezone,
		&i.Lat,
		&i.Lon,
		&i.RegionID,
		&i.RegionName,
		&i.CountryCode,
		&i.CountryName,
		&i.DistanceM,
	)
	return i, err
}

const normalizeQuery = `-- name: NormalizeQuery :one
SELECT normalize_text($1::text)::text AS normalized
`

// Нормализация строки поиска той же функцией, что у name_normalized: пустой результат — 400.
func (q *Queries) NormalizeQuery(ctx context.Context, input string) (string, error) {
	row := q.db.QueryRow(ctx, normalizeQuery, input)
	var normalized string
	err := row.Scan(&normalized)
	return normalized, err
}

const resolveCitySlug = `-- name: ResolveCitySlug :one
SELECT s.city_id FROM (
  SELECT id AS city_id, 0 AS prio FROM cities WHERE slug = $1::text
  UNION ALL
  SELECT h.city_id, 1 AS prio FROM city_slug_history h WHERE h.slug = $1::text
) s
ORDER BY s.prio
LIMIT 1
`

// Город по slug: текущий slug раньше истории (prio 0); видимость проверяет GetVisibleCity.
func (q *Queries) ResolveCitySlug(ctx context.Context, slug string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, resolveCitySlug, slug)
	var city_id uuid.UUID
	err := row.Scan(&city_id)
	return city_id, err
}
