// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import.sql

package geodb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const importCityCandidates = `-- name: ImportCityCandidates :many
SELECT p.geoname_id, p.admin1_code
FROM cities c
JOIN regions r ON r.id = c.region_id,
     geonames_places p
WHERE c.id = $1::uuid
  AND p.country_code = $2
  AND (normalize_text(p.name) = c.name_normalized
       OR EXISTS (SELECT 1 FROM geonames_place_names pn
                  WHERE pn.geoname_id = p.geoname_id AND pn.locale = 'ru'
                    AND pn.name_normalized = c.name_normalized))
  AND (p.admin1_code = r.geoname_admin1_code
       OR (r.geoname_admin1_code IS NULL AND EXISTS (
             SELECT 1
             FROM region_names rn
             JOIN geonames_admin1_names an
               ON an.country_code = p.country_code AND an.admin1_code = p.admin1_code
             WHERE rn.region_id = r.id AND normalize_text(rn.name) = normalize_text(an.name))))
  AND NOT EXISTS (SELECT 1 FROM cities c2 WHERE c2.geoname_id = p.geoname_id)
ORDER BY p.geoname_id
`

type ImportCityCandidatesParams struct {
	CityID      uuid.UUID
	CountryCode string
}

type ImportCityCandidatesRow struct {
	GeonameID  int64
	Admin1Code *string
}

// Места страны с тем же названием (основное или ru, после normalize_text) в том же регионе:
// по geoname_admin1_code региона, а без кода — по названиям региона и admin1. Место, уже
// привязанное к городу, не кандидат. Город без региона кандидатов не получает.
func (q *Queries) ImportCityCandidates(ctx context.Context, arg ImportCityCandidatesParams) ([]ImportCityCandidatesRow, error) {
	rows, err := q.db.Query(ctx, importCityCandidates, arg.CityID, arg.CountryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportCityCandidatesRow
	for rows.Next() {
		var i ImportCityCandidatesRow
		if err := rows.Scan(&i.GeonameID, &i.Admin1Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importCityNamesFromPlace = `-- name: ImportCityNamesFromPlace :execrows
INSERT INTO city_names (city_id, locale, name)
SELECT $1::uuid, pn.locale, pn.name
FROM geonames_place_names pn
WHERE pn.geoname_id = $2::bigint
  AND pn.locale <> $3::text
  AND btrim(pn.name) <> ''
ON CONFLICT DO NOTHING
`

type ImportCityNamesFromPlaceParams struct {
	CityID        uuid.UUID
	GeonameID     int64
	CountryLocale string
}

// Только отсутствующие переводы (§3.3); строку языка страны сверка не создаёт — она источник
// канонического cities.name.
func (q *Queries) ImportCityNamesFromPlace(ctx context.Context, arg ImportCityNamesFromPlaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, importCityNamesFromPlace, arg.CityID, arg.GeonameID, arg.CountryLocale)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importCountry = `-- name: ImportCountry :one

SELECT id, default_locale FROM countries WHERE code = $1
`

type ImportCountryRow struct {
	ID            uuid.UUID
	DefaultLocale string
}

// Импорт GeoNames (спека geo §5.4): журнал geonames_imports, источник geonames_*, сверка
// заведённых городов. Исполняет воркер (роль worker, grants.sql §3.8).
func (q *Queries) ImportCountry(ctx context.Context, code string) (ImportCountryRow, error) {
	row := q.db.QueryRow(ctx, importCountry, code)
	var i ImportCountryRow
	err := row.Scan(&i.ID, &i.DefaultLocale)
	return i, err
}

const importDeleteAdmin1Names = `-- name: ImportDeleteAdmin1Names :exec
DELETE FROM geonames_admin1_names WHERE country_code = $1
`

func (q *Queries) ImportDeleteAdmin1Names(ctx context.Context, countryCode string) error {
	_, err := q.db.Exec(ctx, importDeleteAdmin1Names, countryCode)
	return err
}

const importDeleteGone = `-- name: ImportDeleteGone :execrows
DELETE FROM geonames_places p
WHERE p.country_code = $1
  AND p.import_id <> $2::uuid
  AND NOT EXISTS (SELECT 1 FROM cities c WHERE c.geoname_id = p.geoname_id)
`

type ImportDeleteGoneParams struct {
	CountryCode string
	ImportID    uuid.UUID
}

func (q *Queries) ImportDeleteGone(ctx context.Context, arg ImportDeleteGoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, importDeleteGone, arg.CountryCode, arg.ImportID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importDeletePlaceNames = `-- name: ImportDeletePlaceNames :exec
DELETE FROM geonames_place_names WHERE geoname_id = ANY($1::bigint[])
`

func (q *Queries) ImportDeletePlaceNames(ctx context.Context, geonameID []int64) error {
	_, err := q.db.Exec(ctx, importDeletePlaceNames, geonameID)
	return err
}

const importDeleteStaleAdmin1 = `-- name: ImportDeleteStaleAdmin1 :exec
DELETE FROM geonames_admin1
WHERE country_code = $1
  AND NOT (admin1_code = ANY($2::text[]))
`

type ImportDeleteStaleAdmin1Params struct {
	CountryCode string
	Keep        []string
}

func (q *Queries) ImportDeleteStaleAdmin1(ctx context.Context, arg ImportDeleteStaleAdmin1Params) error {
	_, err := q.db.Exec(ctx, importDeleteStaleAdmin1, arg.CountryCode, arg.Keep)
	return err
}

const importFail = `-- name: ImportFail :execrows
UPDATE geonames_imports
SET status = 'failed', finished_at = $1::timestamptz, error = $2::text,
    source_files = COALESCE($3::jsonb, source_files)
WHERE id = $4::uuid AND status = 'running'
`

type ImportFailParams struct {
	Now         time.Time
	Reason      string
	SourceFiles []byte
	ID          uuid.UUID
}

// source_files — уже скачанные файлы (R27); NULL — ничего не скачано, прежнее значение остаётся.
func (q *Queries) ImportFail(ctx context.Context, arg ImportFailParams) (int64, error) {
	result, err := q.db.Exec(ctx, importFail,
		arg.Now,
		arg.Reason,
		arg.SourceFiles,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importFailStale = `-- name: ImportFailStale :many
UPDATE geonames_imports
SET status = 'failed', finished_at = $1::timestamptz, error = $2::text
WHERE country_code = $3
  AND status = 'running'
  AND started_at < $4::timestamptz
RETURNING id
`

type ImportFailStaleParams struct {
	Now         time.Time
	Reason      string
	CountryCode string
	StaleBefore time.Time
}

// Строки running старше таймаута задачи + 10 минут — процесс убит без итога (шаг 1).
func (q *Queries) ImportFailStale(ctx context.Context, arg ImportFailStaleParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, importFailStale,
		arg.Now,
		arg.Reason,
		arg.CountryCode,
		arg.StaleBefore,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importFindOwnRunning = `-- name: ImportFindOwnRunning :one
SELECT id FROM geonames_imports
WHERE country_code = $1
  AND status = 'running'
  AND river_job_id = $2::bigint
`

type ImportFindOwnRunningParams struct {
	CountryCode string
	RiverJobID  int64
}

// Строка running этой же задачи River — прерванная попытка: она продолжается (шаг 1).
func (q *Queries) ImportFindOwnRunning(ctx context.Context, arg ImportFindOwnRunningParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, importFindOwnRunning, arg.CountryCode, arg.RiverJobID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const importInsertAdmin1Names = `-- name: ImportInsertAdmin1Names :execrows
INSERT INTO geonames_admin1_names (country_code, admin1_code, locale, name)
SELECT $1::text, u.admin1_code, u.locale, u.name
FROM (SELECT unnest($2::text[]) AS admin1_code,
             unnest($3::text[])      AS locale,
             unnest($4::text[])        AS name) AS u
`

type ImportInsertAdmin1NamesParams struct {
	CountryCode string
	Admin1Code  []string
	Locale      []string
	Name        []string
}

func (q *Queries) ImportInsertAdmin1Names(ctx context.Context, arg ImportInsertAdmin1NamesParams) (int64, error) {
	result, err := q.db.Exec(ctx, importInsertAdmin1Names,
		arg.CountryCode,
		arg.Admin1Code,
		arg.Locale,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importInsertPlaceNames = `-- name: ImportInsertPlaceNames :execrows
INSERT INTO geonames_place_names (geoname_id, locale, name)
SELECT u.geoname_id, u.locale, u.name
FROM (SELECT unnest($1::bigint[]) AS geoname_id,
             unnest($2::text[])       AS locale,
             unnest($3::text[])         AS name) AS u
`

type ImportInsertPlaceNamesParams struct {
	GeonameID []int64
	Locale    []string
	Name      []string
}

func (q *Queries) ImportInsertPlaceNames(ctx context.Context, arg ImportInsertPlaceNamesParams) (int64, error) {
	result, err := q.db.Exec(ctx, importInsertPlaceNames, arg.GeonameID, arg.Locale, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importLastSucceededPlaces = `-- name: ImportLastSucceededPlaces :one
SELECT COALESCE(places_upserted, 0)::int AS places
FROM geonames_imports
WHERE country_code = $1 AND status = 'succeeded'
ORDER BY finished_at DESC, started_at DESC
LIMIT 1
`

// Мест в прошлом успешном импорте страны — база порога 90 % (шаг 4).
func (q *Queries) ImportLastSucceededPlaces(ctx context.Context, countryCode string) (int32, error) {
	row := q.db.QueryRow(ctx, importLastSucceededPlaces, countryCode)
	var places int32
	err := row.Scan(&places)
	return places, err
}

const importLinkCity = `-- name: ImportLinkCity :one
UPDATE cities
SET geoname_id = $1::bigint, version = version + 1
WHERE id = $2::uuid AND geoname_id IS NULL
RETURNING version
`

type ImportLinkCityParams struct {
	GeonameID int64
	ID        uuid.UUID
}

func (q *Queries) ImportLinkCity(ctx context.Context, arg ImportLinkCityParams) (int64, error) {
	row := q.db.QueryRow(ctx, importLinkCity, arg.GeonameID, arg.ID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const importLinkRegion = `-- name: ImportLinkRegion :execrows
UPDATE regions r
SET geoname_admin1_code = $1::text
WHERE r.id = $2::uuid
  AND r.geoname_admin1_code IS NULL
  AND NOT EXISTS (SELECT 1 FROM regions r2
                  WHERE r2.country_id = r.country_id
                    AND r2.geoname_admin1_code = $1::text)
`

type ImportLinkRegionParams struct {
	Admin1Code string
	ID         uuid.UUID
}

// Региону, найденному по названию, — код admin1 (если пуст и не занят другим регионом страны:
// уникальность regions_country_admin1_key).
func (q *Queries) ImportLinkRegion(ctx context.Context, arg ImportLinkRegionParams) (int64, error) {
	result, err := q.db.Exec(ctx, importLinkRegion, arg.Admin1Code, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importMarkMissing = `-- name: ImportMarkMissing :many
UPDATE geonames_places p
SET missing_since = COALESCE(p.missing_since, $1::timestamptz)
WHERE p.country_code = $2
  AND p.import_id <> $3::uuid
  AND EXISTS (SELECT 1 FROM cities c WHERE c.geoname_id = p.geoname_id)
RETURNING p.geoname_id
`

type ImportMarkMissingParams struct {
	Now         time.Time
	CountryCode string
	ImportID    uuid.UUID
}

// Пропали из источника, но на них ссылается город: остаются с отметкой и попадают в отчёт (шаг 4).
func (q *Queries) ImportMarkMissing(ctx context.Context, arg ImportMarkMissingParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, importMarkMissing, arg.Now, arg.CountryCode, arg.ImportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var geoname_id int64
		if err := rows.Scan(&geoname_id); err != nil {
			return nil, err
		}
		items = append(items, geoname_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importRegionNamesFromAdmin1 = `-- name: ImportRegionNamesFromAdmin1 :execrows
INSERT INTO region_names (region_id, locale, name)
SELECT $1::uuid, an.locale, an.name
FROM geonames_admin1_names an
WHERE an.country_code = $2
  AND an.admin1_code = $3::text
  AND an.locale <> $4::text
  AND btrim(an.name) <> ''
ON CONFLICT DO NOTHING
`

type ImportRegionNamesFromAdmin1Params struct {
	RegionID      uuid.UUID
	CountryCode   string
	Admin1Code    string
	CountryLocale string
}

func (q *Queries) ImportRegionNamesFromAdmin1(ctx context.Context, arg ImportRegionNamesFromAdmin1Params) (int64, error) {
	result, err := q.db.Exec(ctx, importRegionNamesFromAdmin1,
		arg.RegionID,
		arg.CountryCode,
		arg.Admin1Code,
		arg.CountryLocale,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importRestart = `-- name: ImportRestart :exec
UPDATE geonames_imports SET started_at = $1::timestamptz WHERE id = $2::uuid
`

type ImportRestartParams struct {
	StartedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) ImportRestart(ctx context.Context, arg ImportRestartParams) error {
	_, err := q.db.Exec(ctx, importRestart, arg.StartedAt, arg.ID)
	return err
}

const importStart = `-- name: ImportStart :exec
INSERT INTO geonames_imports (id, country_code, status, started_at, started_by, river_job_id)
VALUES ($1::uuid, $2::text, 'running', $3::timestamptz,
        $4::uuid, $5::bigint)
`

type ImportStartParams struct {
	ID          uuid.UUID
	CountryCode string
	StartedAt   time.Time
	StartedBy   *uuid.UUID
	RiverJobID  *int64
}

func (q *Queries) ImportStart(ctx context.Context, arg ImportStartParams) error {
	_, err := q.db.Exec(ctx, importStart,
		arg.ID,
		arg.CountryCode,
		arg.StartedAt,
		arg.StartedBy,
		arg.RiverJobID,
	)
	return err
}

const importSucceed = `-- name: ImportSucceed :execrows
UPDATE geonames_imports
SET status = 'succeeded', finished_at = $1::timestamptz,
    source_files = $2::jsonb,
    places_upserted = $3::bigint, places_removed = $4::bigint,
    places_missing = $5::bigint, names_upserted = $6::bigint,
    reconciled = $7::jsonb, error = NULL
WHERE id = $8::uuid AND status = 'running'
`

type ImportSucceedParams struct {
	Now            time.Time
	SourceFiles    []byte
	PlacesUpserted int64
	PlacesRemoved  int64
	PlacesMissing  int64
	NamesUpserted  int64
	Reconciled     []byte
	ID             uuid.UUID
}

func (q *Queries) ImportSucceed(ctx context.Context, arg ImportSucceedParams) (int64, error) {
	result, err := q.db.Exec(ctx, importSucceed,
		arg.Now,
		arg.SourceFiles,
		arg.PlacesUpserted,
		arg.PlacesRemoved,
		arg.PlacesMissing,
		arg.NamesUpserted,
		arg.Reconciled,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importUnlinkedCities = `-- name: ImportUnlinkedCities :many
SELECT c.id, c.slug, c.region_id
FROM cities c
JOIN countries co ON co.id = c.country_id
WHERE co.code = $1 AND c.geoname_id IS NULL
ORDER BY c.slug
`

type ImportUnlinkedCitiesRow struct {
	ID       uuid.UUID
	Slug     string
	RegionID *uuid.UUID
}

// Заведённые города страны без geoname_id — кандидаты сверки (шаг 5).
func (q *Queries) ImportUnlinkedCities(ctx context.Context, countryCode string) ([]ImportUnlinkedCitiesRow, error) {
	rows, err := q.db.Query(ctx, importUnlinkedCities, countryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportUnlinkedCitiesRow
	for rows.Next() {
		var i ImportUnlinkedCitiesRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.RegionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importUpsertAdmin1 = `-- name: ImportUpsertAdmin1 :exec
INSERT INTO geonames_admin1 (country_code, admin1_code, geoname_id, ascii_name)
SELECT $1::text, u.admin1_code, u.geoname_id, u.ascii_name
FROM (SELECT unnest($2::text[]) AS admin1_code,
             unnest($3::bigint[]) AS geoname_id,
             unnest($4::text[])   AS ascii_name) AS u
ON CONFLICT (country_code, admin1_code) DO UPDATE SET
    geoname_id = EXCLUDED.geoname_id,
    ascii_name = EXCLUDED.ascii_name
`

type ImportUpsertAdmin1Params struct {
	CountryCode string
	Admin1Code  []string
	GeonameID   []int64
	AsciiName   []string
}

func (q *Queries) ImportUpsertAdmin1(ctx context.Context, arg ImportUpsertAdmin1Params) error {
	_, err := q.db.Exec(ctx, importUpsertAdmin1,
		arg.CountryCode,
		arg.Admin1Code,
		arg.GeonameID,
		arg.AsciiName,
	)
	return err
}

const importUpsertPlaces = `-- name: ImportUpsertPlaces :exec
INSERT INTO geonames_places (geoname_id, country_code, admin1_code, name, ascii_name, feature_code,
                             population, location, timezone, missing_since, import_id)
SELECT u.geoname_id, u.country_code, NULLIF(u.admin1_code, ''), u.name, u.ascii_name, u.feature_code,
       u.population, ST_SetSRID(ST_MakePoint(u.lon, u.lat), 4326)::geography, u.timezone, NULL,
       $1::uuid
FROM (SELECT unnest($2::bigint[])  AS geoname_id,
             unnest($3::text[])  AS country_code,
             unnest($4::text[])   AS admin1_code,
             unnest($5::text[])          AS name,
             unnest($6::text[])    AS ascii_name,
             unnest($7::text[])  AS feature_code,
             unnest($8::bigint[])  AS population,
             unnest($9::float8[])         AS lat,
             unnest($10::float8[])         AS lon,
             unnest($11::text[])      AS timezone) AS u
ON CONFLICT (geoname_id) DO UPDATE SET
    country_code  = EXCLUDED.country_code,
    admin1_code   = EXCLUDED.admin1_code,
    name          = EXCLUDED.name,
    ascii_name    = EXCLUDED.ascii_name,
    feature_code  = EXCLUDED.feature_code,
    population    = EXCLUDED.population,
    location      = EXCLUDED.location,
    timezone      = EXCLUDED.timezone,
    missing_since = NULL,
    import_id     = EXCLUDED.import_id
`

type ImportUpsertPlacesParams struct {
	ImportID    uuid.UUID
	GeonameID   []int64
	CountryCode []string
	Admin1Code  []string
	Name        []string
	AsciiName   []string
	FeatureCode []string
	Population  []int64
	Lat         []float64
	Lon         []float64
	Timezone    []string
}

// Пачка мест (до 1000): массивы одной длины, по элементу на место.
func (q *Queries) ImportUpsertPlaces(ctx context.Context, arg ImportUpsertPlacesParams) error {
	_, err := q.db.Exec(ctx, importUpsertPlaces,
		arg.ImportID,
		arg.GeonameID,
		arg.CountryCode,
		arg.Admin1Code,
		arg.Name,
		arg.AsciiName,
		arg.FeatureCode,
		arg.Population,
		arg.Lat,
		arg.Lon,
		arg.Timezone,
	)
	return err
}
