// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: places.sql

package geodb

import (
	"context"

	"github.com/google/uuid"
)

const getVisiblePlace = `-- name: GetVisiblePlace :one
SELECT p.geoname_id,
       coalesce(pn.name, pd.name, p.name)::text AS name,
       coalesce(CASE WHEN c.id IS NULL THEN coalesce(an.name, ad.name, a.ascii_name)
                     ELSE coalesce(rn.name, r.name) END, '')::text AS region_name,
       co.code::text AS country_code,
       coalesce(con.name, co.name)::text AS country_name,
       c.id AS city_id
FROM geonames_places p
LEFT JOIN cities c ON c.geoname_id = p.geoname_id
LEFT JOIN countries sco ON sco.code = p.country_code
JOIN countries co ON co.id = coalesce(c.country_id, sco.id)
LEFT JOIN geonames_place_names pn ON pn.geoname_id = p.geoname_id AND pn.locale = $1::text
LEFT JOIN geonames_place_names pd ON pd.geoname_id = p.geoname_id AND pd.locale = co.default_locale
LEFT JOIN geonames_admin1 a ON a.country_code = p.country_code AND a.admin1_code = p.admin1_code
LEFT JOIN geonames_admin1_names an
       ON an.country_code = a.country_code AND an.admin1_code = a.admin1_code AND an.locale = $1::text
LEFT JOIN geonames_admin1_names ad
       ON ad.country_code = a.country_code AND ad.admin1_code = a.admin1_code AND ad.locale = co.default_locale
LEFT JOIN regions r ON r.id = c.region_id
LEFT JOIN region_names rn ON rn.region_id = r.id AND rn.locale = $1::text
LEFT JOIN country_names con ON con.country_id = co.id AND con.locale = $1::text
WHERE p.geoname_id = $2::bigint AND co.is_enabled
`

type GetVisiblePlaceParams struct {
	Locale    string
	GeonameID int64
}

type GetVisiblePlaceRow struct {
	GeonameID   int64
	Name        string
	RegionName  string
	CountryCode string
	CountryName string
	CityID      *uuid.UUID
}

// Место для ответа «here» (§4.1). Страна: место заведено городом — страна города (в том числе
// переопределённая админом), иначе страна источника по коду; страны нет в countries или она
// выключена — 0 строк (here = null). Названия: запрошенная локаль → язык страны → name источника;
// регион: у заведённого — регион города (может отсутствовать), иначе admin1 источника; ” — нет.
func (q *Queries) GetVisiblePlace(ctx context.Context, arg GetVisiblePlaceParams) (GetVisiblePlaceRow, error) {
	row := q.db.QueryRow(ctx, getVisiblePlace, arg.Locale, arg.GeonameID)
	var i GetVisiblePlaceRow
	err := row.Scan(
		&i.GeonameID,
		&i.Name,
		&i.RegionName,
		&i.CountryCode,
		&i.CountryName,
		&i.CityID,
	)
	return i, err
}

const placesWithin = `-- name: PlacesWithin :many
SELECT p.geoname_id, p.population,
       ST_Distance(p.location,
                   ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography)::float8
         AS distance_m
FROM geonames_places p
WHERE ST_DWithin(p.location,
                 ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
                 $3::float8)
ORDER BY distance_m, p.geoname_id
`

type PlacesWithinParams struct {
	Lon     float64
	Lat     float64
	RadiusM float64
}

type PlacesWithinRow struct {
	GeonameID  int64
	Population int64
	DistanceM  float64
}

// Кандидаты «here» (спека geo §4.3): места источника в радиусе поиска, ближайшие первыми.
// Накрытие r(population) отбирает Go (domain.CoverRadiusMeters) — константы в одном месте.
func (q *Queries) PlacesWithin(ctx context.Context, arg PlacesWithinParams) ([]PlacesWithinRow, error) {
	rows, err := q.db.Query(ctx, placesWithin, arg.Lon, arg.Lat, arg.RadiusM)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlacesWithinRow
	for rows.Next() {
		var i PlacesWithinRow
		if err := rows.Scan(&i.GeonameID, &i.Population, &i.DistanceM); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
