// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package geodb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Настройки города для других модулей (§7): без фильтра видимости — country_enabled в ответе.
	GetCitySettings(ctx context.Context, id uuid.UUID) (GetCitySettingsRow, error)
	// Город с правилами страны (CityDetails без районов); страна выключена или города нет — 0 строк.
	GetVisibleCity(ctx context.Context, arg GetVisibleCityParams) (GetVisibleCityRow, error)
	// Место для ответа «here» (§4.1). Страна: место заведено городом — страна города (в том числе
	// переопределённая админом), иначе страна источника по коду; страны нет в countries или она
	// выключена — 0 строк (here = null). Названия: запрошенная локаль → язык страны → name источника;
	// регион: у заведённого — регион города (может отсутствовать), иначе admin1 источника; '' — нет.
	GetVisiblePlace(ctx context.Context, arg GetVisiblePlaceParams) (GetVisiblePlaceRow, error)
	// Места страны с тем же названием (основное или ru, после normalize_text) в том же регионе:
	// по geoname_admin1_code региона, а без кода — по названиям региона и admin1. Место, уже
	// привязанное к городу, не кандидат. Город без региона кандидатов не получает.
	ImportCityCandidates(ctx context.Context, arg ImportCityCandidatesParams) ([]ImportCityCandidatesRow, error)
	// Только отсутствующие переводы (§3.3); строку языка страны сверка не создаёт — она источник
	// канонического cities.name.
	ImportCityNamesFromPlace(ctx context.Context, arg ImportCityNamesFromPlaceParams) (int64, error)
	// Импорт GeoNames (спека geo §5.4): журнал geonames_imports, источник geonames_*, сверка
	// заведённых городов. Исполняет воркер (роль worker, grants.sql §3.8).
	ImportCountry(ctx context.Context, code string) (ImportCountryRow, error)
	ImportDeleteAdmin1Names(ctx context.Context, countryCode string) error
	ImportDeleteGone(ctx context.Context, arg ImportDeleteGoneParams) (int64, error)
	ImportDeletePlaceNames(ctx context.Context, geonameID []int64) error
	ImportDeleteStaleAdmin1(ctx context.Context, arg ImportDeleteStaleAdmin1Params) error
	// source_files — уже скачанные файлы (R27); NULL — ничего не скачано, прежнее значение остаётся.
	ImportFail(ctx context.Context, arg ImportFailParams) (int64, error)
	// Строки running старше таймаута задачи + 10 минут — процесс убит без итога (шаг 1).
	ImportFailStale(ctx context.Context, arg ImportFailStaleParams) ([]uuid.UUID, error)
	// Строка running этой же задачи River — прерванная попытка: она продолжается (шаг 1).
	ImportFindOwnRunning(ctx context.Context, arg ImportFindOwnRunningParams) (uuid.UUID, error)
	ImportInsertAdmin1Names(ctx context.Context, arg ImportInsertAdmin1NamesParams) (int64, error)
	ImportInsertPlaceNames(ctx context.Context, arg ImportInsertPlaceNamesParams) (int64, error)
	// Мест в прошлом успешном импорте страны — база порога 90 % (шаг 4).
	ImportLastSucceededPlaces(ctx context.Context, countryCode string) (int32, error)
	ImportLinkCity(ctx context.Context, arg ImportLinkCityParams) (int64, error)
	// Региону, найденному по названию, — код admin1 (если пуст и не занят другим регионом страны:
	// уникальность regions_country_admin1_key).
	ImportLinkRegion(ctx context.Context, arg ImportLinkRegionParams) (int64, error)
	// Пропали из источника, но на них ссылается город: остаются с отметкой и попадают в отчёт (шаг 4).
	ImportMarkMissing(ctx context.Context, arg ImportMarkMissingParams) ([]int64, error)
	ImportRegionNamesFromAdmin1(ctx context.Context, arg ImportRegionNamesFromAdmin1Params) (int64, error)
	ImportRestart(ctx context.Context, arg ImportRestartParams) error
	ImportStart(ctx context.Context, arg ImportStartParams) error
	ImportSucceed(ctx context.Context, arg ImportSucceedParams) (int64, error)
	// Заведённые города страны без geoname_id — кандидаты сверки (шаг 5).
	ImportUnlinkedCities(ctx context.Context, countryCode string) ([]ImportUnlinkedCitiesRow, error)
	ImportUpsertAdmin1(ctx context.Context, arg ImportUpsertAdmin1Params) error
	// Пачка мест (до 1000): массивы одной длины, по элементу на место.
	ImportUpsertPlaces(ctx context.Context, arg ImportUpsertPlacesParams) error
	// Районы города без архивных (§3.2).
	ListActiveDistricts(ctx context.Context, cityID uuid.UUID) ([]ListActiveDistrictsRow, error)
	// Публичный список городов (спека geo §4.2). Видимость — только страны is_enabled (§4.1).
	// Названия: строка *_names запрошенной локали, иначе каноническое name (язык страны);
	// locale = '' — локаль не согласована: строк с пустой локалью нет (CHECK ^[a-z]{2}$), все названия
	// канонические. Регион: region_id NULL — региона нет, region_name тогда ''.
	// Порядок: ранг статуса (live 0, pilot 1, waitlist 2), population по убыванию, id; курсор —
	// строго после (after_rank, after_population, after_id) в этом порядке.
	// statuses пуст — без фильтра; country '' — без фильтра; q_prefix '' — без поиска. q_prefix уже
	// нормализован (normalize_text оставляет только [a-zа-яё0-9], поэтому % и _ в нём невозможны).
	// Перед «||» — sqlc.arg(x), не @x: префиксный «@» захватил бы всё выражение (см. ratelimit.sql).
	ListCities(ctx context.Context, arg ListCitiesParams) ([]ListCitiesRow, error)
	// Ближайший видимый город pilot/live по centroid без ограничения расстояния (§4.3): KNN «<->»
	// по GiST-индексу, расстояние — ST_Distance по geography (сфероид, антимеридиан учтён).
	NearestOpenCity(ctx context.Context, arg NearestOpenCityParams) (NearestOpenCityRow, error)
	// Нормализация строки поиска той же функцией, что у name_normalized: пустой результат — 400.
	NormalizeQuery(ctx context.Context, input string) (string, error)
	// Кандидаты «here» (спека geo §4.3): места источника в радиусе поиска, ближайшие первыми.
	// Накрытие r(population) отбирает Go (domain.CoverRadiusMeters) — константы в одном месте.
	PlacesWithin(ctx context.Context, arg PlacesWithinParams) ([]PlacesWithinRow, error)
	// Город по slug: текущий slug раньше истории (prio 0); видимость проверяет GetVisibleCity.
	ResolveCitySlug(ctx context.Context, slug string) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
