// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package geodb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Настройки города для других модулей (§7): без фильтра видимости — country_enabled в ответе.
	GetCitySettings(ctx context.Context, id uuid.UUID) (GetCitySettingsRow, error)
	// Город с правилами страны (CityDetails без районов); страна выключена или города нет — 0 строк.
	GetVisibleCity(ctx context.Context, arg GetVisibleCityParams) (GetVisibleCityRow, error)
	// Место для ответа «here» (§4.1). Страна: место заведено городом — страна города (в том числе
	// переопределённая админом), иначе страна источника по коду; страны нет в countries или она
	// выключена — 0 строк (here = null). Названия: запрошенная локаль → язык страны → name источника;
	// регион: у заведённого — регион города (может отсутствовать), иначе admin1 источника; '' — нет.
	GetVisiblePlace(ctx context.Context, arg GetVisiblePlaceParams) (GetVisiblePlaceRow, error)
	// Районы города без архивных (§3.2).
	ListActiveDistricts(ctx context.Context, cityID uuid.UUID) ([]ListActiveDistrictsRow, error)
	// Публичный список городов (спека geo §4.2). Видимость — только страны is_enabled (§4.1).
	// Названия: строка *_names запрошенной локали, иначе каноническое name (язык страны);
	// locale = '' — локаль не согласована: строк с пустой локалью нет (CHECK ^[a-z]{2}$), все названия
	// канонические. Регион: region_id NULL — региона нет, region_name тогда ''.
	// Порядок: ранг статуса (live 0, pilot 1, waitlist 2), population по убыванию, id; курсор —
	// строго после (after_rank, after_population, after_id) в этом порядке.
	// statuses пуст — без фильтра; country '' — без фильтра; q_prefix '' — без поиска. q_prefix уже
	// нормализован (normalize_text оставляет только [a-zа-яё0-9], поэтому % и _ в нём невозможны).
	// Перед «||» — sqlc.arg(x), не @x: префиксный «@» захватил бы всё выражение (см. ratelimit.sql).
	ListCities(ctx context.Context, arg ListCitiesParams) ([]ListCitiesRow, error)
	// Ближайший видимый город pilot/live по centroid без ограничения расстояния (§4.3): KNN «<->»
	// по GiST-индексу, расстояние — ST_Distance по geography (сфероид, антимеридиан учтён).
	NearestOpenCity(ctx context.Context, arg NearestOpenCityParams) (NearestOpenCityRow, error)
	// Нормализация строки поиска той же функцией, что у name_normalized: пустой результат — 400.
	NormalizeQuery(ctx context.Context, input string) (string, error)
	// Кандидаты «here» (спека geo §4.3): места источника в радиусе поиска, ближайшие первыми.
	// Накрытие r(population) отбирает Go (domain.CoverRadiusMeters) — константы в одном месте.
	PlacesWithin(ctx context.Context, arg PlacesWithinParams) ([]PlacesWithinRow, error)
	// Город по slug: текущий slug раньше истории (prio 0); видимость проверяет GetVisibleCity.
	ResolveCitySlug(ctx context.Context, slug string) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
