// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package eventsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advanceCursor = `-- name: AdvanceCursor :exec
UPDATE event_cursors SET version = $1, updated_at = now()
WHERE subscriber = $2 AND aggregate_type = $3 AND aggregate_id = $4
  AND version < $1
`

type AdvanceCursorParams struct {
	Version       int64
	Subscriber    string
	AggregateType string
	AggregateID   uuid.UUID
}

func (q *Queries) AdvanceCursor(ctx context.Context, arg AdvanceCursorParams) error {
	_, err := q.db.Exec(ctx, advanceCursor,
		arg.Version,
		arg.Subscriber,
		arg.AggregateType,
		arg.AggregateID,
	)
	return err
}

const deleteOldInbox = `-- name: DeleteOldInbox :execrows
DELETE FROM event_inbox WHERE (subscriber, event_id) IN (
  SELECT subscriber, event_id FROM event_inbox WHERE processed_at < now() - interval '30 days' LIMIT $1
)
`

func (q *Queries) DeleteOldInbox(ctx context.Context, batch int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldInbox, batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldPublished = `-- name: DeleteOldPublished :execrows
DELETE FROM outbox WHERE id IN (
  SELECT id FROM outbox WHERE published_at < now() - interval '30 days' LIMIT $1
)
`

// Чистка (спека §6.5, §9.3): опубликованное и обработанное старше 30 дней, пачками.
func (q *Queries) DeleteOldPublished(ctx context.Context, batch int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldPublished, batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureCursor = `-- name: EnsureCursor :exec
INSERT INTO event_cursors (subscriber, aggregate_type, aggregate_id, version)
VALUES ($1, $2, $3, 0)
ON CONFLICT DO NOTHING
`

type EnsureCursorParams struct {
	Subscriber    string
	AggregateType string
	AggregateID   uuid.UUID
}

// Курсор создаётся заранее, чтобы параллельные события одного агрегата встали в очередь на
// блокировке строки, а не разошлись на «строки ещё нет».
func (q *Queries) EnsureCursor(ctx context.Context, arg EnsureCursorParams) error {
	_, err := q.db.Exec(ctx, ensureCursor, arg.Subscriber, arg.AggregateType, arg.AggregateID)
	return err
}

const eventIDsForReplay = `-- name: EventIDsForReplay :many
SELECT id FROM outbox
WHERE event_type = $1 AND occurred_at >= $2
ORDER BY occurred_at, id
`

type EventIDsForReplayParams struct {
	EventType string
	Since     time.Time
}

func (q *Queries) EventIDsForReplay(ctx context.Context, arg EventIDsForReplayParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, eventIDsForReplay, arg.EventType, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, event_type, schema_version, aggregate_type, aggregate_id, aggregate_version, occurred_at, payload, trace, published_at FROM outbox WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Outbox, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.SchemaVersion,
		&i.AggregateType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.OccurredAt,
		&i.Payload,
		&i.Trace,
		&i.PublishedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec

INSERT INTO outbox (id, event_type, schema_version, aggregate_type, aggregate_id, aggregate_version, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEventParams struct {
	ID               uuid.UUID
	EventType        string
	SchemaVersion    int32
	AggregateType    string
	AggregateID      uuid.UUID
	AggregateVersion int64
	Payload          []byte
}

// События платформы (спека бэкенда §6.5). Владелец outbox, event_inbox, event_cursors — platform.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.EventType,
		arg.SchemaVersion,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.Payload,
	)
	return err
}

const insertInbox = `-- name: InsertInbox :execrows
INSERT INTO event_inbox (subscriber, event_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertInboxParams struct {
	Subscriber string
	EventID    uuid.UUID
}

// 0 строк — событие этим подписчиком уже обработано.
func (q *Queries) InsertInbox(ctx context.Context, arg InsertInboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInbox, arg.Subscriber, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockCursor = `-- name: LockCursor :one
SELECT version FROM event_cursors
WHERE subscriber = $1 AND aggregate_type = $2 AND aggregate_id = $3
FOR UPDATE
`

type LockCursorParams struct {
	Subscriber    string
	AggregateType string
	AggregateID   uuid.UUID
}

func (q *Queries) LockCursor(ctx context.Context, arg LockCursorParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockCursor, arg.Subscriber, arg.AggregateType, arg.AggregateID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const lockUnpublished = `-- name: LockUnpublished :many
SELECT id, event_type, schema_version, aggregate_type, aggregate_id, aggregate_version, occurred_at, payload, trace, published_at FROM outbox
WHERE published_at IS NULL
ORDER BY occurred_at, id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// Пачка для relay; SKIP LOCKED — несколько воркеров берут разные строки.
func (q *Queries) LockUnpublished(ctx context.Context, batch int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, lockUnpublished, batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.SchemaVersion,
			&i.AggregateType,
			&i.AggregateID,
			&i.AggregateVersion,
			&i.OccurredAt,
			&i.Payload,
			&i.Trace,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPublished = `-- name: MarkPublished :exec
UPDATE outbox SET published_at = now() WHERE id = ANY($1::uuid[])
`

func (q *Queries) MarkPublished(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPublished, ids)
	return err
}
