// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package eventsdb

import (
	"time"

	"github.com/google/uuid"
)

type Outbox struct {
	ID               uuid.UUID
	EventType        string
	SchemaVersion    int32
	AggregateType    string
	AggregateID      uuid.UUID
	AggregateVersion int64
	OccurredAt       time.Time
	Payload          []byte
	Trace            []byte
	PublishedAt      *time.Time
}
