// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package eventsdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AdvanceCursor(ctx context.Context, arg AdvanceCursorParams) error
	DeleteOldInbox(ctx context.Context, batch int32) (int64, error)
	// Чистка (спека §6.5, §9.3): опубликованное и обработанное старше 30 дней, пачками.
	DeleteOldPublished(ctx context.Context, batch int32) (int64, error)
	// Курсор создаётся заранее, чтобы параллельные события одного агрегата встали в очередь на
	// блокировке строки, а не разошлись на «строки ещё нет».
	EnsureCursor(ctx context.Context, arg EnsureCursorParams) error
	EventIDsForReplay(ctx context.Context, arg EventIDsForReplayParams) ([]uuid.UUID, error)
	GetEvent(ctx context.Context, id uuid.UUID) (Outbox, error)
	// События платформы (спека бэкенда §6.5). Владелец outbox, event_inbox, event_cursors — platform.
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	// 0 строк — событие этим подписчиком уже обработано.
	InsertInbox(ctx context.Context, arg InsertInboxParams) (int64, error)
	LockCursor(ctx context.Context, arg LockCursorParams) (int64, error)
	// Пачка для relay; SKIP LOCKED — несколько воркеров берут разные строки.
	LockUnpublished(ctx context.Context, batch int32) ([]Outbox, error)
	MarkPublished(ctx context.Context, ids []uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
