// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package idempotencydb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claim = `-- name: Claim :one
INSERT INTO idempotency_keys AS k (user_id, key, endpoint, request_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, key) DO UPDATE
SET endpoint = excluded.endpoint,
    request_hash = excluded.request_hash,
    response_status = NULL,
    response_headers = NULL,
    response_body = NULL,
    created_at = now(),
    expires_at = now() + interval '24 hours'
WHERE k.expires_at <= now()
RETURNING created_at
`

type ClaimParams struct {
	UserID      uuid.UUID
	Key         string
	Endpoint    string
	RequestHash string
}

// Вставка ключа внутри бизнес-транзакции. Просроченный ключ переиспользуется; живой — 0 строк.
// Параллельный дубль ждёт здесь на уникальном индексе, пока первая транзакция не закончится
// (не дольше lock_timeout).
func (q *Queries) Claim(ctx context.Context, arg ClaimParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, claim,
		arg.UserID,
		arg.Key,
		arg.Endpoint,
		arg.RequestHash,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const currentLockTimeout = `-- name: CurrentLockTimeout :one
SELECT current_setting('lock_timeout')::text
`

func (q *Queries) CurrentLockTimeout(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, currentLockTimeout)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteExpired = `-- name: DeleteExpired :execrows
DELETE FROM idempotency_keys
WHERE expires_at <= now()
  AND (user_id, key) IN (SELECT user_id, key FROM idempotency_keys WHERE expires_at <= now() LIMIT $1)
`

// Условие срока — и на внешнем DELETE: подзапрос видит снимок до коммита параллельного Claim, а
// после ожидания блокировки перепроверяется только WHERE внешнего оператора. Без него ключ,
// переиспользованный в эту секунду, удалился бы — и повтор исполнил бы действие второй раз.
func (q *Queries) DeleteExpired(ctx context.Context, batch int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpired, batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const get = `-- name: Get :one

SELECT request_hash, response_status, response_headers, response_body
FROM idempotency_keys
WHERE user_id = $1 AND key = $2 AND expires_at > now()
`

type GetParams struct {
	UserID uuid.UUID
	Key    string
}

type GetRow struct {
	RequestHash     string
	ResponseStatus  *int32
	ResponseHeaders []byte
	ResponseBody    []byte
}

// Идемпотентность мутирующих запросов (спека бэкенда §6.4). Владелец idempotency_keys — platform.
// Время — время базы. Срок ключа 24 ч задают DEFAULT таблицы и Claim (при переиспользовании) —
// менять вместе.
func (q *Queries) Get(ctx context.Context, arg GetParams) (GetRow, error) {
	row := q.db.QueryRow(ctx, get, arg.UserID, arg.Key)
	var i GetRow
	err := row.Scan(
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
	)
	return i, err
}

const saveResponse = `-- name: SaveResponse :execrows
UPDATE idempotency_keys
SET response_status = $1, response_headers = $2, response_body = $3
WHERE user_id = $4 AND key = $5 AND request_hash = $6 AND response_status IS NULL
`

type SaveResponseParams struct {
	Status      *int32
	Headers     []byte
	Body        []byte
	UserID      uuid.UUID
	Key         string
	RequestHash string
}

// Ответ сохраняется после коммита бизнес-транзакции; 0 строк — транзакция откатилась (ключа нет).
func (q *Queries) SaveResponse(ctx context.Context, arg SaveResponseParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveResponse,
		arg.Status,
		arg.Headers,
		arg.Body,
		arg.UserID,
		arg.Key,
		arg.RequestHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLockTimeout = `-- name: SetLockTimeout :exec
SELECT set_config('lock_timeout', $1::text, true)
`

// Только до конца текущей транзакции (is_local = true).
func (q *Queries) SetLockTimeout(ctx context.Context, value string) error {
	_, err := q.db.Exec(ctx, setLockTimeout, value)
	return err
}
