// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: humancheck.sql

package humancheckdb

import (
	"context"
	"time"
)

const deleteExpired = `-- name: DeleteExpired :execrows
DELETE FROM humancheck_spent
WHERE signature IN (SELECT signature FROM humancheck_spent WHERE expires_at < $1::timestamptz LIMIT $2)
`

type DeleteExpiredParams struct {
	Now   time.Time
	Batch int32
}

func (q *Queries) DeleteExpired(ctx context.Context, arg DeleteExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpired, arg.Now, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const spend = `-- name: Spend :execrows

INSERT INTO humancheck_spent (signature, expires_at) VALUES ($1, $2)
ON CONFLICT (signature) DO NOTHING
`

type SpendParams struct {
	Signature string
	ExpiresAt time.Time
}

// Израсходованные решения PoW (спека бэкенда §6.7). Владелец humancheck_spent — platform.
// 0 строк — решение уже предъявляли: повтор.
func (q *Queries) Spend(ctx context.Context, arg SpendParams) (int64, error) {
	result, err := q.db.Exec(ctx, spend, arg.Signature, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
