// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package humancheckdb

import (
	"context"
)

type Querier interface {
	DeleteExpired(ctx context.Context, arg DeleteExpiredParams) (int64, error)
	// Израсходованные решения PoW (спека бэкенда §6.7). Владелец humancheck_spent — platform.
	// 0 строк — решение уже предъявляли: повтор.
	Spend(ctx context.Context, arg SpendParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
