// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flags.sql

package flagsdb

import (
	"context"
)

const getFlag = `-- name: GetFlag :one
SELECT key, enabled_globally FROM feature_flags WHERE key = $1
`

type GetFlagRow struct {
	Key             string
	EnabledGlobally bool
}

func (q *Queries) GetFlag(ctx context.Context, key string) (GetFlagRow, error) {
	row := q.db.QueryRow(ctx, getFlag, key)
	var i GetFlagRow
	err := row.Scan(&i.Key, &i.EnabledGlobally)
	return i, err
}
