// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package flagsdb

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AchievementBranch string

const (
	AchievementBranchParticipation AchievementBranch = "participation"
	AchievementBranchSport         AchievementBranch = "sport"
	AchievementBranchReliability   AchievementBranch = "reliability"
	AchievementBranchOrganizer     AchievementBranch = "organizer"
)

func (e *AchievementBranch) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AchievementBranch(s)
	case string:
		*e = AchievementBranch(s)
	default:
		return fmt.Errorf("unsupported scan type for AchievementBranch: %T", src)
	}
	return nil
}

type NullAchievementBranch struct {
	AchievementBranch AchievementBranch
	Valid             bool // Valid is true if AchievementBranch is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAchievementBranch) Scan(value interface{}) error {
	if value == nil {
		ns.AchievementBranch, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AchievementBranch.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAchievementBranch) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AchievementBranch), nil
}

type ApplicationStatus string

const (
	ApplicationStatusPending   ApplicationStatus = "pending"
	ApplicationStatusApproved  ApplicationStatus = "approved"
	ApplicationStatusRejected  ApplicationStatus = "rejected"
	ApplicationStatusWithdrawn ApplicationStatus = "withdrawn"
)

func (e *ApplicationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationStatus(s)
	case string:
		*e = ApplicationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationStatus: %T", src)
	}
	return nil
}

type NullApplicationStatus struct {
	ApplicationStatus ApplicationStatus
	Valid             bool // Valid is true if ApplicationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationStatus), nil
}

type ChallengeStatus string

const (
	ChallengeStatusOpen      ChallengeStatus = "open"
	ChallengeStatusMatched   ChallengeStatus = "matched"
	ChallengeStatusCancelled ChallengeStatus = "cancelled"
	ChallengeStatusExpired   ChallengeStatus = "expired"
)

func (e *ChallengeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChallengeStatus(s)
	case string:
		*e = ChallengeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChallengeStatus: %T", src)
	}
	return nil
}

type NullChallengeStatus struct {
	ChallengeStatus ChallengeStatus
	Valid           bool // Valid is true if ChallengeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChallengeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChallengeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChallengeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChallengeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChallengeStatus), nil
}

type CityStatus string

const (
	CityStatusWaitlist CityStatus = "waitlist"
	CityStatusPilot    CityStatus = "pilot"
	CityStatusLive     CityStatus = "live"
)

func (e *CityStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CityStatus(s)
	case string:
		*e = CityStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CityStatus: %T", src)
	}
	return nil
}

type NullCityStatus struct {
	CityStatus CityStatus
	Valid      bool // Valid is true if CityStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCityStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CityStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CityStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCityStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CityStatus), nil
}

type CompetitionKind string

const (
	CompetitionKindCup           CompetitionKind = "cup"
	CompetitionKindRoundRobin    CompetitionKind = "round_robin"
	CompetitionKindGroupsPlayoff CompetitionKind = "groups_playoff"
	CompetitionKindLeague        CompetitionKind = "league"
)

func (e *CompetitionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompetitionKind(s)
	case string:
		*e = CompetitionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CompetitionKind: %T", src)
	}
	return nil
}

type NullCompetitionKind struct {
	CompetitionKind CompetitionKind
	Valid           bool // Valid is true if CompetitionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompetitionKind) Scan(value interface{}) error {
	if value == nil {
		ns.CompetitionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompetitionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompetitionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompetitionKind), nil
}

type CurrencyKind string

const (
	CurrencyKindPoints  CurrencyKind = "points"
	CurrencyKindCredits CurrencyKind = "credits"
)

func (e *CurrencyKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CurrencyKind(s)
	case string:
		*e = CurrencyKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CurrencyKind: %T", src)
	}
	return nil
}

type NullCurrencyKind struct {
	CurrencyKind CurrencyKind
	Valid        bool // Valid is true if CurrencyKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrencyKind) Scan(value interface{}) error {
	if value == nil {
		ns.CurrencyKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CurrencyKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrencyKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CurrencyKind), nil
}

type ItemAcquisition string

const (
	ItemAcquisitionDefault      ItemAcquisition = "default"
	ItemAcquisitionPoints       ItemAcquisition = "points"
	ItemAcquisitionCredits      ItemAcquisition = "credits"
	ItemAcquisitionAchievement  ItemAcquisition = "achievement"
	ItemAcquisitionSubscription ItemAcquisition = "subscription"
)

func (e *ItemAcquisition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemAcquisition(s)
	case string:
		*e = ItemAcquisition(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemAcquisition: %T", src)
	}
	return nil
}

type NullItemAcquisition struct {
	ItemAcquisition ItemAcquisition
	Valid           bool // Valid is true if ItemAcquisition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemAcquisition) Scan(value interface{}) error {
	if value == nil {
		ns.ItemAcquisition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemAcquisition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemAcquisition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemAcquisition), nil
}

type ItemKind string

const (
	ItemKindAvatar          ItemKind = "avatar"
	ItemKindFrame           ItemKind = "frame"
	ItemKindBoots           ItemKind = "boots"
	ItemKindKit             ItemKind = "kit"
	ItemKindSocks           ItemKind = "socks"
	ItemKindBackground      ItemKind = "background"
	ItemKindTeamCrest       ItemKind = "team_crest"
	ItemKindTeamColors      ItemKind = "team_colors"
	ItemKindTeamCover       ItemKind = "team_cover"
	ItemKindRatingAnimation ItemKind = "rating_animation"
)

func (e *ItemKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemKind(s)
	case string:
		*e = ItemKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemKind: %T", src)
	}
	return nil
}

type NullItemKind struct {
	ItemKind ItemKind
	Valid    bool // Valid is true if ItemKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemKind) Scan(value interface{}) error {
	if value == nil {
		ns.ItemKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemKind), nil
}

type JoinRequestKind string

const (
	JoinRequestKindRequest JoinRequestKind = "request"
	JoinRequestKindInvite  JoinRequestKind = "invite"
)

func (e *JoinRequestKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JoinRequestKind(s)
	case string:
		*e = JoinRequestKind(s)
	default:
		return fmt.Errorf("unsupported scan type for JoinRequestKind: %T", src)
	}
	return nil
}

type NullJoinRequestKind struct {
	JoinRequestKind JoinRequestKind
	Valid           bool // Valid is true if JoinRequestKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJoinRequestKind) Scan(value interface{}) error {
	if value == nil {
		ns.JoinRequestKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JoinRequestKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJoinRequestKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JoinRequestKind), nil
}

type MatchEventType string

const (
	MatchEventTypeGoal    MatchEventType = "goal"
	MatchEventTypeOwnGoal MatchEventType = "own_goal"
	MatchEventTypeAssist  MatchEventType = "assist"
	MatchEventTypeGkShift MatchEventType = "gk_shift"
)

func (e *MatchEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchEventType(s)
	case string:
		*e = MatchEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchEventType: %T", src)
	}
	return nil
}

type NullMatchEventType struct {
	MatchEventType MatchEventType
	Valid          bool // Valid is true if MatchEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchEventType) Scan(value interface{}) error {
	if value == nil {
		ns.MatchEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchEventType), nil
}

type MatchFormat string

const (
	MatchFormat5x5   MatchFormat = "5x5"
	MatchFormat6x6   MatchFormat = "6x6"
	MatchFormat7x7   MatchFormat = "7x7"
	MatchFormat8x8   MatchFormat = "8x8"
	MatchFormat9x9   MatchFormat = "9x9"
	MatchFormat11x11 MatchFormat = "11x11"
)

func (e *MatchFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchFormat(s)
	case string:
		*e = MatchFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchFormat: %T", src)
	}
	return nil
}

type NullMatchFormat struct {
	MatchFormat MatchFormat
	Valid       bool // Valid is true if MatchFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchFormat) Scan(value interface{}) error {
	if value == nil {
		ns.MatchFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchFormat), nil
}

type MatchSide string

const (
	MatchSideHome MatchSide = "home"
	MatchSideAway MatchSide = "away"
)

func (e *MatchSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchSide(s)
	case string:
		*e = MatchSide(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchSide: %T", src)
	}
	return nil
}

type NullMatchSide struct {
	MatchSide MatchSide
	Valid     bool // Valid is true if MatchSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchSide) Scan(value interface{}) error {
	if value == nil {
		ns.MatchSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchSide), nil
}

type MatchStatus string

const (
	MatchStatusDraft          MatchStatus = "draft"
	MatchStatusScheduled      MatchStatus = "scheduled"
	MatchStatusConfirmed      MatchStatus = "confirmed"
	MatchStatusLive           MatchStatus = "live"
	MatchStatusAwaitingReport MatchStatus = "awaiting_report"
	MatchStatusCompleted      MatchStatus = "completed"
	MatchStatusCancelled      MatchStatus = "cancelled"
	MatchStatusExpired        MatchStatus = "expired"
)

func (e *MatchStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchStatus(s)
	case string:
		*e = MatchStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchStatus: %T", src)
	}
	return nil
}

type NullMatchStatus struct {
	MatchStatus MatchStatus
	Valid       bool // Valid is true if MatchStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MatchStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchStatus), nil
}

type MatchType string

const (
	MatchTypeFriendly MatchType = "friendly"
	MatchTypePickup   MatchType = "pickup"
	MatchTypeTraining MatchType = "training"
)

func (e *MatchType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchType(s)
	case string:
		*e = MatchType(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchType: %T", src)
	}
	return nil
}

type NullMatchType struct {
	MatchType MatchType
	Valid     bool // Valid is true if MatchType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchType) Scan(value interface{}) error {
	if value == nil {
		ns.MatchType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchType), nil
}

type MatchVisibility string

const (
	MatchVisibilityTeamOnly   MatchVisibility = "team_only"
	MatchVisibilityInviteOnly MatchVisibility = "invite_only"
	MatchVisibilityPublic     MatchVisibility = "public"
)

func (e *MatchVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchVisibility(s)
	case string:
		*e = MatchVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchVisibility: %T", src)
	}
	return nil
}

type NullMatchVisibility struct {
	MatchVisibility MatchVisibility
	Valid           bool // Valid is true if MatchVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.MatchVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchVisibility), nil
}

type MembershipStatus string

const (
	MembershipStatusPending MembershipStatus = "pending"
	MembershipStatusActive  MembershipStatus = "active"
	MembershipStatusLeft    MembershipStatus = "left"
	MembershipStatusRemoved MembershipStatus = "removed"
)

func (e *MembershipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipStatus(s)
	case string:
		*e = MembershipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipStatus: %T", src)
	}
	return nil
}

type NullMembershipStatus struct {
	MembershipStatus MembershipStatus
	Valid            bool // Valid is true if MembershipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipStatus), nil
}

type ModerationStatus string

const (
	ModerationStatusPending  ModerationStatus = "pending"
	ModerationStatusApproved ModerationStatus = "approved"
	ModerationStatusRejected ModerationStatus = "rejected"
	ModerationStatusMerged   ModerationStatus = "merged"
)

func (e *ModerationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModerationStatus(s)
	case string:
		*e = ModerationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ModerationStatus: %T", src)
	}
	return nil
}

type NullModerationStatus struct {
	ModerationStatus ModerationStatus
	Valid            bool // Valid is true if ModerationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModerationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ModerationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModerationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModerationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModerationStatus), nil
}

type NotificationCategory string

const (
	NotificationCategoryTeamMatchCreated NotificationCategory = "team_match_created"
	NotificationCategoryTeamJoinRequest  NotificationCategory = "team_join_request"
	NotificationCategoryMatchAlmostFull  NotificationCategory = "match_almost_full"
	NotificationCategoryMatchReminder    NotificationCategory = "match_reminder"
	NotificationCategoryMatchCancelled   NotificationCategory = "match_cancelled"
	NotificationCategoryReportPending    NotificationCategory = "report_pending"
	NotificationCategoryCityNewTeam      NotificationCategory = "city_new_team"
	NotificationCategoryCityNewMatch     NotificationCategory = "city_new_match"
	NotificationCategoryAchievement      NotificationCategory = "achievement"
	NotificationCategoryWeeklyDigest     NotificationCategory = "weekly_digest"
)

func (e *NotificationCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationCategory(s)
	case string:
		*e = NotificationCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationCategory: %T", src)
	}
	return nil
}

type NullNotificationCategory struct {
	NotificationCategory NotificationCategory
	Valid                bool // Valid is true if NotificationCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationCategory) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationCategory), nil
}

type NotificationChannel string

const (
	NotificationChannelPush  NotificationChannel = "push"
	NotificationChannelEmail NotificationChannel = "email"
	NotificationChannelInApp NotificationChannel = "in_app"
)

func (e *NotificationChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationChannel(s)
	case string:
		*e = NotificationChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationChannel: %T", src)
	}
	return nil
}

type NullNotificationChannel struct {
	NotificationChannel NotificationChannel
	Valid               bool // Valid is true if NotificationChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationChannel) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationChannel), nil
}

type PitchKind string

const (
	PitchKindOutdoor PitchKind = "outdoor"
	PitchKindIndoor  PitchKind = "indoor"
	PitchKindCovered PitchKind = "covered"
)

func (e *PitchKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PitchKind(s)
	case string:
		*e = PitchKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PitchKind: %T", src)
	}
	return nil
}

type NullPitchKind struct {
	PitchKind PitchKind
	Valid     bool // Valid is true if PitchKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPitchKind) Scan(value interface{}) error {
	if value == nil {
		ns.PitchKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PitchKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPitchKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PitchKind), nil
}

type PitchSurface string

const (
	PitchSurfaceArtificial PitchSurface = "artificial"
	PitchSurfaceNatural    PitchSurface = "natural"
	PitchSurfaceGround     PitchSurface = "ground"
	PitchSurfaceParquet    PitchSurface = "parquet"
	PitchSurfaceAsphalt    PitchSurface = "asphalt"
	PitchSurfaceSand       PitchSurface = "sand"
)

func (e *PitchSurface) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PitchSurface(s)
	case string:
		*e = PitchSurface(s)
	default:
		return fmt.Errorf("unsupported scan type for PitchSurface: %T", src)
	}
	return nil
}

type NullPitchSurface struct {
	PitchSurface PitchSurface
	Valid        bool // Valid is true if PitchSurface is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPitchSurface) Scan(value interface{}) error {
	if value == nil {
		ns.PitchSurface, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PitchSurface.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPitchSurface) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PitchSurface), nil
}

type PlayerPosition string

const (
	PlayerPositionGK  PlayerPosition = "GK"
	PlayerPositionDEF PlayerPosition = "DEF"
	PlayerPositionMID PlayerPosition = "MID"
	PlayerPositionFWD PlayerPosition = "FWD"
	PlayerPositionANY PlayerPosition = "ANY"
)

func (e *PlayerPosition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlayerPosition(s)
	case string:
		*e = PlayerPosition(s)
	default:
		return fmt.Errorf("unsupported scan type for PlayerPosition: %T", src)
	}
	return nil
}

type NullPlayerPosition struct {
	PlayerPosition PlayerPosition
	Valid          bool // Valid is true if PlayerPosition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlayerPosition) Scan(value interface{}) error {
	if value == nil {
		ns.PlayerPosition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlayerPosition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlayerPosition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlayerPosition), nil
}

type ReportState string

const (
	ReportStateDraft     ReportState = "draft"
	ReportStateSubmitted ReportState = "submitted"
	ReportStateConfirmed ReportState = "confirmed"
	ReportStateDisputed  ReportState = "disputed"
	ReportStateResolved  ReportState = "resolved"
	ReportStateExpired   ReportState = "expired"
)

func (e *ReportState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportState(s)
	case string:
		*e = ReportState(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportState: %T", src)
	}
	return nil
}

type NullReportState struct {
	ReportState ReportState
	Valid       bool // Valid is true if ReportState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportState) Scan(value interface{}) error {
	if value == nil {
		ns.ReportState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportState), nil
}

type ReportTarget string

const (
	ReportTargetUser    ReportTarget = "user"
	ReportTargetTeam    ReportTarget = "team"
	ReportTargetMatch   ReportTarget = "match"
	ReportTargetPitch   ReportTarget = "pitch"
	ReportTargetComment ReportTarget = "comment"
)

func (e *ReportTarget) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportTarget(s)
	case string:
		*e = ReportTarget(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportTarget: %T", src)
	}
	return nil
}

type NullReportTarget struct {
	ReportTarget ReportTarget
	Valid        bool // Valid is true if ReportTarget is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportTarget) Scan(value interface{}) error {
	if value == nil {
		ns.ReportTarget, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportTarget.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportTarget) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportTarget), nil
}

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type RoleName string

const (
	RoleNamePlayer        RoleName = "player"
	RoleNameCaptain       RoleName = "captain"
	RoleNameViceCaptain   RoleName = "vice_captain"
	RoleNameCityModerator RoleName = "city_moderator"
	RoleNameAdmin         RoleName = "admin"
)

func (e *RoleName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleName(s)
	case string:
		*e = RoleName(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleName: %T", src)
	}
	return nil
}

type NullRoleName struct {
	RoleName RoleName
	Valid    bool // Valid is true if RoleName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleName) Scan(value interface{}) error {
	if value == nil {
		ns.RoleName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleName), nil
}

type RoleScope string

const (
	RoleScopeGlobal  RoleScope = "global"
	RoleScopeCountry RoleScope = "country"
	RoleScopeCity    RoleScope = "city"
	RoleScopeTeam    RoleScope = "team"
)

func (e *RoleScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleScope(s)
	case string:
		*e = RoleScope(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleScope: %T", src)
	}
	return nil
}

type NullRoleScope struct {
	RoleScope RoleScope
	Valid     bool // Valid is true if RoleScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleScope) Scan(value interface{}) error {
	if value == nil {
		ns.RoleScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleScope), nil
}

type RsvpStatus string

const (
	RsvpStatusInvited   RsvpStatus = "invited"
	RsvpStatusRequested RsvpStatus = "requested"
	RsvpStatusConfirmed RsvpStatus = "confirmed"
	RsvpStatusDeclined  RsvpStatus = "declined"
	RsvpStatusWaitlist  RsvpStatus = "waitlist"
	RsvpStatusKicked    RsvpStatus = "kicked"
)

func (e *RsvpStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RsvpStatus(s)
	case string:
		*e = RsvpStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RsvpStatus: %T", src)
	}
	return nil
}

type NullRsvpStatus struct {
	RsvpStatus RsvpStatus
	Valid      bool // Valid is true if RsvpStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRsvpStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RsvpStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RsvpStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRsvpStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RsvpStatus), nil
}

type SanctionKind string

const (
	SanctionKindWarning      SanctionKind = "warning"
	SanctionKindFeatureBlock SanctionKind = "feature_block"
	SanctionKindSuspension   SanctionKind = "suspension"
	SanctionKindBan          SanctionKind = "ban"
)

func (e *SanctionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SanctionKind(s)
	case string:
		*e = SanctionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for SanctionKind: %T", src)
	}
	return nil
}

type NullSanctionKind struct {
	SanctionKind SanctionKind
	Valid        bool // Valid is true if SanctionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSanctionKind) Scan(value interface{}) error {
	if value == nil {
		ns.SanctionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SanctionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSanctionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SanctionKind), nil
}

type SkillLevel string

const (
	SkillLevelNovice          SkillLevel = "novice"
	SkillLevelNovicePlus      SkillLevel = "novice_plus"
	SkillLevelAmateur         SkillLevel = "amateur"
	SkillLevelAmateurPlus     SkillLevel = "amateur_plus"
	SkillLevelExperienced     SkillLevel = "experienced"
	SkillLevelExperiencedPlus SkillLevel = "experienced_plus"
	SkillLevelSemiPro         SkillLevel = "semi_pro"
)

func (e *SkillLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SkillLevel(s)
	case string:
		*e = SkillLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for SkillLevel: %T", src)
	}
	return nil
}

type NullSkillLevel struct {
	SkillLevel SkillLevel
	Valid      bool // Valid is true if SkillLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSkillLevel) Scan(value interface{}) error {
	if value == nil {
		ns.SkillLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SkillLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSkillLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SkillLevel), nil
}

type SubscriptionSource string

const (
	SubscriptionSourceAppStore   SubscriptionSource = "app_store"
	SubscriptionSourceGooglePlay SubscriptionSource = "google_play"
	SubscriptionSourceWeb        SubscriptionSource = "web"
	SubscriptionSourceGrant      SubscriptionSource = "grant"
	SubscriptionSourceLootbox    SubscriptionSource = "lootbox"
)

func (e *SubscriptionSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionSource(s)
	case string:
		*e = SubscriptionSource(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionSource: %T", src)
	}
	return nil
}

type NullSubscriptionSource struct {
	SubscriptionSource SubscriptionSource
	Valid              bool // Valid is true if SubscriptionSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionSource) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionSource), nil
}

type SubscriptionTier string

const (
	SubscriptionTierFree       SubscriptionTier = "free"
	SubscriptionTierPlayerPro  SubscriptionTier = "player_pro"
	SubscriptionTierCaptainPro SubscriptionTier = "captain_pro"
)

func (e *SubscriptionTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionTier(s)
	case string:
		*e = SubscriptionTier(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionTier: %T", src)
	}
	return nil
}

type NullSubscriptionTier struct {
	SubscriptionTier SubscriptionTier
	Valid            bool // Valid is true if SubscriptionTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionTier) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionTier), nil
}

type TeamStatus string

const (
	TeamStatusActive   TeamStatus = "active"
	TeamStatusPaused   TeamStatus = "paused"
	TeamStatusArchived TeamStatus = "archived"
)

func (e *TeamStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamStatus(s)
	case string:
		*e = TeamStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamStatus: %T", src)
	}
	return nil
}

type NullTeamStatus struct {
	TeamStatus TeamStatus
	Valid      bool // Valid is true if TeamStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TeamStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamStatus), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusBanned    UserStatus = "banned"
	UserStatusDeleted   UserStatus = "deleted"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AbuseReport struct {
	ID         pgtype.UUID
	ReporterID pgtype.UUID
	TargetType ReportTarget
	TargetID   pgtype.UUID
	CityID     pgtype.UUID
	Category   string
	Body       *string
	Status     ApplicationStatus
	DecidedBy  pgtype.UUID
	DecidedAt  pgtype.Timestamptz
	Resolution *string
	CreatedAt  pgtype.Timestamptz
}

type Achievement struct {
	Code        string
	Branch      AchievementBranch
	Name        string
	Description string
	Threshold   *int32
	Tier        int16
	ItemID      pgtype.UUID
	PointsAward int64
	IsActive    bool
}

type AdDismissal struct {
	UserID      pgtype.UUID
	PlacementID pgtype.UUID
	DismissedAt pgtype.Timestamptz
}

type AdPlacement struct {
	ID        pgtype.UUID
	Slot      string
	CityID    pgtype.UUID
	PitchID   pgtype.UUID
	Title     string
	Body      *string
	ImageUrl  *string
	TargetUrl *string
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type AnomalyFlag struct {
	ID          pgtype.UUID
	SubjectType string
	SubjectID   pgtype.UUID
	CityID      pgtype.UUID
	Rule        string
	Details     []byte
	Status      ApplicationStatus
	ReviewedBy  pgtype.UUID
	ReviewedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type AuditLog struct {
	ID          pgtype.UUID
	ActorUserID pgtype.UUID
	ActorRole   *string
	Action      string
	ObjectType  string
	ObjectID    pgtype.UUID
	Before      []byte
	After       []byte
	Reason      *string
	Ip          *netip.Addr
	UserAgent   *string
	CreatedAt   pgtype.Timestamptz
}

type CaptainApplication struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	CityID          pgtype.UUID
	ProposedFormat  *string
	ProposedPitch   *string
	PlayFrequency   *string
	ContactLink     *string
	Note            *string
	Status          ApplicationStatus
	IsProbationary  bool
	ReviewedBy      pgtype.UUID
	ReviewedAt      pgtype.Timestamptz
	RejectionReason *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type CaptaincyTransfer struct {
	ID          pgtype.UUID
	TeamID      pgtype.UUID
	FromUserID  pgtype.UUID
	ToUserID    pgtype.UUID
	InitiatedBy string
	Status      ApplicationStatus
	CreatedAt   pgtype.Timestamptz
	DecidedAt   pgtype.Timestamptz
}

type CatalogItem struct {
	ID              pgtype.UUID
	Kind            ItemKind
	Code            string
	Name            string
	Description     *string
	AssetUrl        *string
	Acquisition     ItemAcquisition
	PricePoints     *int64
	PriceCredits    *int64
	AchievementCode *string
	IsTeamItem      bool
	IsActive        bool
	SortOrder       int32
	CreatedAt       pgtype.Timestamptz
}

type Challenge struct {
	ID             pgtype.UUID
	CityID         pgtype.UUID
	TeamID         pgtype.UUID
	PitchID        pgtype.UUID
	DistrictID     pgtype.UUID
	Format         MatchFormat
	WindowFrom     pgtype.Timestamptz
	WindowTo       pgtype.Timestamptz
	MinAge         *int16
	MaxAge         *int16
	ShareCost      bool
	Note           *string
	Status         ChallengeStatus
	MatchedMatchID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type ChallengeResponse struct {
	ID          pgtype.UUID
	ChallengeID pgtype.UUID
	TeamID      pgtype.UUID
	Message     *string
	Status      ApplicationStatus
	CreatedAt   pgtype.Timestamptz
}

type City struct {
	ID             pgtype.UUID
	CountryID      pgtype.UUID
	RegionID       pgtype.UUID
	Name           string
	NameNormalized *string
	Slug           string
	Timezone       string
	Centroid       *string
	Status         CityStatus
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type CitySetting struct {
	CityID        pgtype.UUID
	CityName      string
	Timezone      string
	Status        CityStatus
	CountryID     pgtype.UUID
	CountryCode   string
	Currency      string
	DefaultLocale string
	MinSignupAge  int16
	AgeOfMajority int16
}

type Competition struct {
	ID               pgtype.UUID
	CityID           pgtype.UUID
	Name             string
	Slug             string
	Kind             CompetitionKind
	Format           MatchFormat
	OrganizerID      pgtype.UUID
	StartsOn         pgtype.Date
	EndsOn           pgtype.Date
	MinAge           *int16
	MaxAge           *int16
	PrizeDescription *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type CompetitionTeam struct {
	CompetitionID pgtype.UUID
	TeamID        pgtype.UUID
	Seed          *int16
	JoinedAt      pgtype.Timestamptz
}

type Country struct {
	ID            pgtype.UUID
	Code          string
	Name          string
	Currency      string
	DefaultLocale string
	PhonePrefix   string
	WeekStartsOn  int16
	MinSignupAge  int16
	AgeOfMajority int16
	IsEnabled     bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type District struct {
	ID             pgtype.UUID
	CityID         pgtype.UUID
	Name           string
	NameNormalized *string
	CreatedAt      pgtype.Timestamptz
}

type FeatureFlag struct {
	Key             string
	Description     string
	EnabledGlobally bool
	EnabledCityIds  []pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
}

type IdempotencyKey struct {
	UserID         pgtype.UUID
	Key            string
	Endpoint       string
	RequestHash    string
	ResponseStatus *int32
	ResponseBody   []byte
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type LedgerEntry struct {
	ID           int64
	UserID       pgtype.UUID
	Kind         CurrencyKind
	Delta        int64
	BalanceAfter int64
	Reason       string
	RefType      *string
	RefID        pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type LootboxGrant struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TypeCode   string
	GrantedFor string
	GrantedAt  pgtype.Timestamptz
	OpenedAt   pgtype.Timestamptz
	Result     []byte
}

type LootboxType struct {
	Code        string
	Name        string
	Description *string
	Contents    []byte
	IsActive    bool
}

type Match struct {
	ID                pgtype.UUID
	CityID            pgtype.UUID
	PitchID           pgtype.UUID
	CompetitionID     pgtype.UUID
	Type              MatchType
	Visibility        MatchVisibility
	Status            MatchStatus
	Format            MatchFormat
	HomeTeamID        pgtype.UUID
	AwayTeamID        pgtype.UUID
	StartsAt          pgtype.Timestamptz
	EndsAt            pgtype.Timestamptz
	Slot              pgtype.Range[pgtype.Timestamptz]
	BlocksPitch       bool
	MinAge            *int16
	MaxAge            *int16
	IsFree            bool
	RentTotalMinor    *int64
	Currency          *string
	PayeeUserID       pgtype.UUID
	GkRotation        bool
	GkRotationMinutes *int16
	GkRotationGoals   *int16
	SlotsTotal        int16
	CreatedBy         pgtype.UUID
	CancelledAt       pgtype.Timestamptz
	CancelReason      *string
	RescheduleCount   int16
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type MatchComment struct {
	ID        pgtype.UUID
	MatchID   pgtype.UUID
	UserID    pgtype.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type MatchEvent struct {
	ID           pgtype.UUID
	MatchID      pgtype.UUID
	Type         MatchEventType
	Side         MatchSide
	UserID       pgtype.UUID
	AssistUserID pgtype.UUID
	Minute       *int16
	GkMinutes    *int16
	CreatedAt    pgtype.Timestamptz
}

type MatchParticipant struct {
	ID            pgtype.UUID
	MatchID       pgtype.UUID
	UserID        pgtype.UUID
	TeamID        pgtype.UUID
	Side          *MatchSide
	Rsvp          RsvpStatus
	RsvpAt        pgtype.Timestamptz
	Attended      *bool
	SelfConfirmed bool
	WasLate       bool
	CancelledAt   pgtype.Timestamptz
	IsLateCancel  bool
	ShareMinor    *int64
	Paid          bool
	PaidMarkedAt  pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type MatchRating struct {
	MatchID   pgtype.UUID
	RaterID   pgtype.UUID
	RatedID   pgtype.UUID
	Rating    int16
	CreatedAt pgtype.Timestamptz
}

type MatchReport struct {
	ID                 pgtype.UUID
	MatchID            pgtype.UUID
	HomeScore          int16
	AwayScore          int16
	SubmittedBy        pgtype.UUID
	SubmittedAt        pgtype.Timestamptz
	ConfirmedBy        pgtype.UUID
	ConfirmedAt        pgtype.Timestamptz
	State              ReportState
	DisputeReason      *string
	DisputedAt         pgtype.Timestamptz
	ResolvedBy         pgtype.UUID
	ResolvedAt         pgtype.Timestamptz
	CountsTowardsStats bool
}

type MatchSlot struct {
	ID         pgtype.UUID
	MatchID    pgtype.UUID
	Side       MatchSide
	SlotNo     int16
	Position   PlayerPosition
	UserID     pgtype.UUID
	IsReserved bool
	CreatedAt  pgtype.Timestamptz
}

type MatchVote struct {
	MatchID   pgtype.UUID
	VoterID   pgtype.UUID
	NomineeID pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type NicknameChange struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	OldValue  string
	NewValue  string
	CreatedAt pgtype.Timestamptz
}

type NicknameReservation struct {
	NicknameNormalized string
	PreviousUserID     pgtype.UUID
	ReleasedAt         pgtype.Timestamptz
	ExpiresAt          pgtype.Timestamptz
}

type Notification struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Category    NotificationCategory
	Title       string
	Body        string
	DeepLink    *string
	RefType     *string
	RefID       pgtype.UUID
	ScheduledAt pgtype.Timestamptz
	SentAt      pgtype.Timestamptz
	ReadAt      pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type NotificationPreference struct {
	UserID   pgtype.UUID
	Category NotificationCategory
	Channel  NotificationChannel
	Enabled  bool
}

type NotificationSetting struct {
	UserID         pgtype.UUID
	QuietHoursFrom pgtype.Time
	QuietHoursTo   pgtype.Time
	AllMuted       bool
	UpdatedAt      pgtype.Timestamptz
}

type Outbox struct {
	ID            int64
	AggregateType string
	AggregateID   pgtype.UUID
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
	Attempts      int32
	LastError     *string
}

type PaymentFlag struct {
	UserID          pgtype.UUID
	DistinctMarkers int16
	IsPublic        bool
	FirstMarkedAt   pgtype.Timestamptz
	LastMarkedAt    pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	DisputedAt      pgtype.Timestamptz
	ComputedAt      pgtype.Timestamptz
}

type PaymentFlagDispute struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	NoteID    pgtype.UUID
	Reason    string
	Status    ApplicationStatus
	DecidedBy pgtype.UUID
	DecidedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type PaymentNote struct {
	ID        pgtype.UUID
	MatchID   pgtype.UUID
	UserID    pgtype.UUID
	TeamID    pgtype.UUID
	MarkedBy  pgtype.UUID
	Unpaid    bool
	ClearedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Pitch struct {
	ID                pgtype.UUID
	CityID            pgtype.UUID
	DistrictID        pgtype.UUID
	Name              string
	Address           string
	Location          string
	Surface           PitchSurface
	Kind              PitchKind
	Formats           []MatchFormat
	HasLighting       bool
	HasChangingRooms  bool
	HasParking        bool
	IsBookable        bool
	IsFree            bool
	TypicalPriceMinor *int64
	Currency          *string
	AdminPhone        *string
	AdminNote         *string
	PhotoUrls         []string
	SubmittedBy       pgtype.UUID
	Status            ModerationStatus
	ReviewedBy        pgtype.UUID
	ReviewedAt        pgtype.Timestamptz
	RejectReason      *string
	MergedIntoID      pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type PlayerStatsDaily struct {
	UserID          pgtype.UUID
	StatDate        pgtype.Date
	Format          MatchFormat
	Matches         int32
	Goals           int32
	Assists         int32
	Wins            int32
	Draws           int32
	Losses          int32
	GkMinutes       int32
	MvpAwards       int32
	AvgRating       pgtype.Numeric
	DiversityWeight pgtype.Numeric
	ComputedAt      pgtype.Timestamptz
}

type PositionReservation struct {
	ID           pgtype.UUID
	MatchID      pgtype.UUID
	UserID       pgtype.UUID
	TeamID       pgtype.UUID
	Position     PlayerPosition
	CreatedAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	RevokedBy    pgtype.UUID
	RevokeReason *string
	Compensated  bool
}

type Prediction struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	MatchID       pgtype.UUID
	StakeKind     CurrencyKind
	Stake         int64
	PredictedHome int16
	PredictedAway int16
	CreatedAt     pgtype.Timestamptz
	SettledAt     pgtype.Timestamptz
	Payout        *int64
}

type PushToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Provider  string
	Token     string
	Locale    *string
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Quest struct {
	Code          string
	Name          string
	Description   string
	Period        string
	Target        int32
	RewardPoints  int64
	RewardLootbox *string
	IsActive      bool
}

type Referral struct {
	ID          pgtype.UUID
	ReferrerID  pgtype.UUID
	ReferredID  pgtype.UUID
	Code        string
	CreatedAt   pgtype.Timestamptz
	QualifiedAt pgtype.Timestamptz
}

type Region struct {
	ID        pgtype.UUID
	CountryID pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type ReliabilityResetRequest struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Status    ApplicationStatus
	DecidedBy pgtype.UUID
	DecidedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type ReliabilitySnapshot struct {
	UserID             pgtype.UUID
	WindowMatches      int16
	ConfirmedCount     int16
	AttendedCount      int16
	RequestsCount      int16
	PlayedCount        int16
	LateCancels        int16
	LateArrivals       int16
	CurrentStreak      int16
	AvgResponseMinutes *int32
	IsNewcomer         bool
	ComputedAt         pgtype.Timestamptz
}

type ReservedNickname struct {
	NicknameNormalized string
	Reason             string
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	FinalizedAt  pgtype.Timestamptz
	ScheduledAt  pgtype.Timestamptz
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	LeaderID  string
	Name      string
}

type RiverNotification struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Payload   string
	Topic     string
}

type RiverQueue struct {
	Name      string
	CreatedAt pgtype.Timestamptz
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RoleAssignment struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Role      RoleName
	ScopeType RoleScope
	ScopeID   pgtype.UUID
	GrantedBy pgtype.UUID
	GrantedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Sanction struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Kind      SanctionKind
	Feature   *string
	Reason    string
	IssuedBy  pgtype.UUID
	StartsAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	RefreshHash   string
	FamilyID      pgtype.UUID
	ParentID      pgtype.UUID
	DeviceName    *string
	DeviceOs      *string
	Ip            *netip.Addr
	UserAgent     *string
	CreatedAt     pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	RevokedReason *string
}

type Subscription struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Tier        SubscriptionTier
	Source      SubscriptionSource
	ExternalID  *string
	StartsAt    pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	AutoRenew   bool
	CancelledAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Team struct {
	ID             pgtype.UUID
	CityID         pgtype.UUID
	Name           string
	NameNormalized *string
	DisplayName    string
	Slug           string
	CaptainID      pgtype.UUID
	ViceCaptainID  pgtype.UUID
	PrimaryFormat  MatchFormat
	RosterLimit    int16
	MinAge         *int16
	MaxAge         *int16
	CrestItemID    pgtype.UUID
	Colors         []byte
	Description    *string
	Status         TeamStatus
	IsProbationary bool
	RenamedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type TeamInventory struct {
	TeamID     pgtype.UUID
	ItemID     pgtype.UUID
	BoughtBy   pgtype.UUID
	AcquiredAt pgtype.Timestamptz
}

type TeamJoinRequest struct {
	ID        pgtype.UUID
	TeamID    pgtype.UUID
	UserID    pgtype.UUID
	Kind      JoinRequestKind
	Message   *string
	Status    ApplicationStatus
	DecidedBy pgtype.UUID
	DecidedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type TeamMember struct {
	ID           pgtype.UUID
	TeamID       pgtype.UUID
	UserID       pgtype.UUID
	Status       MembershipStatus
	Position     *PlayerPosition
	ShirtNumber  *int16
	JoinedAt     pgtype.Timestamptz
	LeftAt       pgtype.Timestamptz
	RemovedBy    pgtype.UUID
	RemoveReason *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type TeamRating struct {
	TeamID      pgtype.UUID
	Format      MatchFormat
	Elo         int32
	Reliability pgtype.Numeric
	UpdatedAt   pgtype.Timestamptz
}

type TeamSlugHistory struct {
	Slug      string
	TeamID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type TeamStatReset struct {
	ID            pgtype.UUID
	TeamID        pgtype.UUID
	RequestedBy   pgtype.UUID
	Reason        string
	Status        ApplicationStatus
	DecidedBy     pgtype.UUID
	DecidedAt     pgtype.Timestamptz
	EffectiveFrom pgtype.Date
	CreatedAt     pgtype.Timestamptz
}

type TeamStatsDaily struct {
	TeamID           pgtype.UUID
	StatDate         pgtype.Date
	Format           MatchFormat
	MatchesPlayed    int16
	MatchesCreated   int16
	MatchesCancelled int16
	Reschedules      int16
	MatchesPerMonth  pgtype.Numeric
	MedianAttendance pgtype.Numeric
	AvgFillRate      pgtype.Numeric
	CorePlayers      int16
	TypicalWeekday   *int16
	TypicalHour      *int16
	MedianShareMinor *int64
	Currency         *string
	Wins             int16
	Draws            int16
	Losses           int16
	GoalsFor         int16
	GoalsAgainst     int16
	IsEstablished    bool
	ComputedAt       pgtype.Timestamptz
}

type User struct {
	ID                 pgtype.UUID
	Email              *string
	EmailVerifiedAt    pgtype.Timestamptz
	Phone              *string
	PhoneVerifiedAt    pgtype.Timestamptz
	Nickname           string
	NicknameNormalized *string
	DisplayName        *string
	BirthDate          pgtype.Date
	CityID             pgtype.UUID
	PrimaryPosition    PlayerPosition
	SecondaryPosition  *PlayerPosition
	ClaimedSkill       SkillLevel
	ConfirmedSkill     *SkillLevel
	PreferredFoot      *string
	HeightCm           *int16
	ShirtNumber        *int16
	FavouriteClub      *string
	Motto              *string
	Locale             string
	Timezone           *string
	AvatarItemID       pgtype.UUID
	Status             UserStatus
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type UserAchievement struct {
	UserID     pgtype.UUID
	Code       string
	UnlockedAt pgtype.Timestamptz
	Progress   int32
}

type UserInventory struct {
	UserID      pgtype.UUID
	ItemID      pgtype.UUID
	AcquiredVia ItemAcquisition
	AcquiredAt  pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type UserQuest struct {
	UserID      pgtype.UUID
	Code        string
	PeriodStart pgtype.Date
	Progress    int32
	CompletedAt pgtype.Timestamptz
	ClaimedAt   pgtype.Timestamptz
}

type Wallet struct {
	UserID    pgtype.UUID
	Kind      CurrencyKind
	Balance   int64
	UpdatedAt pgtype.Timestamptz
}
