// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package flagsdb

import (
	"context"
)

type Querier interface {
	GetFlag(ctx context.Context, key string) (GetFlagRow, error)
	// Включён ли флаг в городе: глобально или город в списке. 0 строк — флага нет.
	IsEnabled(ctx context.Context, arg IsEnabledParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
