// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package flagsdb

import (
	"context"
)

type Querier interface {
	GetFlag(ctx context.Context, key string) (GetFlagRow, error)
}

var _ Querier = (*Queries)(nil)
