// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ratelimitdb

import (
	"context"
	"time"
)

type Querier interface {
	// Счётчик сигнала риска: расходуется всегда, даже сверх порога.
	Add(ctx context.Context, arg AddParams) error
	// Строка с tat в прошлом ничего не ограничивает. Пачками — короткие транзакции.
	DeleteExpired(ctx context.Context, arg DeleteExpiredParams) (int64, error)
	GetTAT(ctx context.Context, key string) (time.Time, error)
	// Rate limit по GCRA (спека бэкенда §6.6). Владелец rate_limits — platform. Время — из часов
	// приложения (@now): тесты двигают их без ожидания.
	// Перед «+» — sqlc.arg(now), не @now: «@» в PostgreSQL ещё и префиксный оператор с приоритетом
	// ниже «+», и «@now::timestamptz + x» разбирается как «@(now::timestamptz + x)» — sqlc ломает запрос.
	// Запрос влезает в всплеск — tat сдвигается, строка возвращается; не влезает — 0 строк,
	// tat не меняется. Один оператор: гонок между проверкой и записью нет.
	Take(ctx context.Context, arg TakeParams) (time.Time, error)
}

var _ Querier = (*Queries)(nil)
