// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratelimit.sql

package ratelimitdb

import (
	"context"
	"time"
)

const add = `-- name: Add :exec
INSERT INTO rate_limits AS r (key, tat)
VALUES ($1, $2::timestamptz + make_interval(secs => $3::float8))
ON CONFLICT (key) DO UPDATE
SET tat = greatest(r.tat, $2::timestamptz) + make_interval(secs => $3::float8)
`

type AddParams struct {
	Key       string
	Now       time.Time
	IntervalS float64
}

// Счётчик сигнала риска: расходуется всегда, даже сверх порога.
func (q *Queries) Add(ctx context.Context, arg AddParams) error {
	_, err := q.db.Exec(ctx, add, arg.Key, arg.Now, arg.IntervalS)
	return err
}

const deleteExpired = `-- name: DeleteExpired :execrows
DELETE FROM rate_limits
WHERE key IN (SELECT key FROM rate_limits WHERE tat < $1::timestamptz LIMIT $2)
`

type DeleteExpiredParams struct {
	Now   time.Time
	Batch int32
}

// Строка с tat в прошлом ничего не ограничивает. Пачками — короткие транзакции.
func (q *Queries) DeleteExpired(ctx context.Context, arg DeleteExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpired, arg.Now, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTAT = `-- name: GetTAT :one
SELECT tat FROM rate_limits WHERE key = $1
`

func (q *Queries) GetTAT(ctx context.Context, key string) (time.Time, error) {
	row := q.db.QueryRow(ctx, getTAT, key)
	var tat time.Time
	err := row.Scan(&tat)
	return tat, err
}

const take = `-- name: Take :one

INSERT INTO rate_limits AS r (key, tat)
VALUES ($1, $2::timestamptz + make_interval(secs => $3::float8))
ON CONFLICT (key) DO UPDATE
SET tat = greatest(r.tat, $2::timestamptz) + make_interval(secs => $3::float8)
WHERE greatest(r.tat, $2::timestamptz) + make_interval(secs => $3::float8)
      <= $2::timestamptz + make_interval(secs => $4::float8)
RETURNING tat
`

type TakeParams struct {
	Key       string
	Now       time.Time
	IntervalS float64
	WindowS   float64
}

// Rate limit по GCRA (спека бэкенда §6.6). Владелец rate_limits — platform. Время — из часов
// приложения (@now): тесты двигают их без ожидания.
// Перед «+» — sqlc.arg(now), не @now: «@» в PostgreSQL ещё и префиксный оператор с приоритетом
// ниже «+», и «@now::timestamptz + x» разбирается как «@(now::timestamptz + x)» — sqlc ломает запрос.
// Запрос влезает в всплеск — tat сдвигается, строка возвращается; не влезает — 0 строк,
// tat не меняется. Один оператор: гонок между проверкой и записью нет.
func (q *Queries) Take(ctx context.Context, arg TakeParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, take,
		arg.Key,
		arg.Now,
		arg.IntervalS,
		arg.WindowS,
	)
	var tat time.Time
	err := row.Scan(&tat)
	return tat, err
}
