name: packages
on:
  push:
    branches: [main]
    paths: &paths
      - 'packages/**'
      - 'contracts/**'
      - 'design/tools/**'
      - 'pnpm-workspace.yaml'
      - 'pnpm-lock.yaml'
      - 'package.json'
      - 'eslint.config.mjs'
      - 'Taskfile.yml'
      - '.github/workflows/packages.yml'
  pull_request:
    paths: *paths
permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: tools/go.mod
          cache-dependency-path: '**/go.sum'
      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
      - run: bash scripts/bootstrap.sh
      - run: ./task packages:ci design:test
